"""The credits fragment for steps 30 and 31: tools/credits/textures-sky.json.

Every licence quote below is checked, whitespace-normalised, against the pinned file it is quoted
from (texsky_sources), so a quote can never drift from its source. Numbers come from the shipped
textures.json / sky.json. Both steps call write(); it writes once both files exist, and the result
does not depend on which step ran last.
"""
import json
import os
import re

import common
import texsky_sources as T
from paths import DATA, TOOLS

RAW = 'https://raw.githubusercontent.com/'


def _norm(s):
    return re.sub(r'\s+', ' ', s).strip()


def _quoted(path, *fragments):
    """Assert that every fragment occurs in the file (whitespace-normalised); return them joined."""
    text = _norm(open(path, encoding='utf-8', errors='replace').read())
    for f in fragments:
        assert _norm(f) in text, f'quote not found in {path}: {f[:80]}'
    return fragments


def _raw(key):
    (repo, commit), path, _sha = T.GIT_FILES[key]
    return f'{RAW}{repo.split("github.com/")[1]}/{commit}/{path}'


def _usgs_url(key):
    return T.USGS + T.USGS_FILES[key][0]


def write():
    tex_path, sky_path = os.path.join(DATA, 'tex', 'textures.json'), os.path.join(DATA, 'sky', 'sky.json')
    if not (os.path.exists(tex_path) and os.path.exists(sky_path)):
        print('credits: textures-sky.json is written once both tex/textures.json and sky/sky.json exist')
        return
    tex = json.load(open(tex_path, encoding='utf-8'))
    B = tex['bodies']
    C = tex['colours']
    R = common.RETRIEVED
    pct = lambda k: f'{100 * B[k]["nodata_fraction"]:.1f} %'

    stel = T.git('stel_credits')
    q_sun, = _quoted(stel, 'The Sun map was created by Ruslan Kabatsayev from the images taken by SDO HMI. The map '
                           'is under the Creative Commons Attribution-ShareAlike 4.0 International license.')
    q_moon, = _quoted(stel, 'Moon albedo map was generated by Ruslan Kabatsayev from Hapke-normalized LROC WAC data '
                            'for visible-light wavelengths, plus empirically-normalized data for 643 nm to cover the '
                            'polar areas. The spectra were converted to linear sRGB, then scaled up by a factor of 4, '
                            'and then the sRGB inverse transfer function was applied. The polar areas, being '
                            'monochromatic in the original data set, were colored using a fit to the equatorial '
                            'sectors. After this the image was color-balanced to yield the grayish look of the '
                            'texture instead of the natural beige color of the lunar surface. The map is under the '
                            'Creative Commons Attribution-ShareAlike 4.0 International license.')
    q_eo, = _quoted(stel, '"Any and all materials published on the Earth Observatory are freely available for '
                          're-publication or re-use, except where copyright is indicated."')
    q_bm, = _quoted(T.git('bluemarble_dgml'), '<license short="NASA / Public Domain">Source: NASA Goddard Space Flight '
                                              'Center Earth Observatory http://earthobservatory.nasa.gov/Newsroom/'
                                              'BlueMarble, License: Public Domain</license>')
    q_cl, = _quoted(T.git('night_dgml'), '<license short="NOAA NGDC, NASA / Public Domain">Source: Marc Imhoff of NASA '
                                         'GSFC; Christopher Elvidge of NOAA NGDC; Craig Mayhew and Robert Simmon, NASA '
                                         'GSFC, License: Public Domain</license>')
    q_jpl = _quoted(T.git('jpl_image_policy'),
                    'may be used for any purpose without prior permission, subject to the special cases noted below',
                    'to use a credit line in connection with images',
                    'Some image and video materials on JPL public web sites are owned by organizations other than '
                    'JPL or NASA. These owners have agreed to make their images and video available for journalistic, '
                    'educational and personal uses, but restrictions are placed on commercial uses.')
    import zipfile
    jmap = zipfile.ZipFile(T.usgs('usgs_mapfiles')).read('maps/jupiter/jupiter_simp_cyl.map').decode('latin-1')
    assert 'Image credit by NASA/JPL/Space Science Institute.' in jmap and 'PIA07782' in jmap
    q_kar_note = _quoted(T.git('karkoschka_lbl'), 'DATA_SET_ID = "ESO-J/S/N/U-SPECTROPHOTOMETER-4-V2.0"',
                         'Low-resolution data from: Methane, Ammonia, and Temperature Measurements of the Jovian '
                         'Planets and Titan from CCD-Spectrophotometry by Erich Karkoschka (ICARUS 1998).')
    q_mit, = _quoted(T.git('starfield_license'), 'MIT License Copyright (c) 2024 Matthew Goodman')
    q_tsis = _quoted(T.git('tsis_csv'), 'TSIS-1 Hybrid Solar Reference Spectrum (HSRS) version 2, resampled to 1 nm box means.',
                     'Source: Coddington et al. (2023), Earth and Space Science, doi:10.1029/2022EA002637')
    q_aws = _quoted(T.git('aws_gaia_yaml'), 'License: Attribution required.',
                    'This [HATS](https://hats.readthedocs.io/en/stable)-formatted catalog was produced by the LSST '
                    'Interdisciplinary Network for Collaboration and Computing.')
    q_cel, = _quoted(T.git('celestia_gaia_license'), 'SPDX-License-Identifier: LicenseRef-CC-BY-NC-3.0-IGO')
    q_ack, = _quoted(T.git('athyg_ack'), 'This work has made use of data from the European Space Agency (ESA) mission '
                                         'Gaia (https://www.cosmos.esa.int/gaia), processed by the Gaia Data Processing '
                                         'and Analysis Consortium (DPAC, https://www.cosmos.esa.int/web/gaia/dpac/'
                                         'consortium). Funding for the DPAC has been provided by national institutions, '
                                         'in particular the institutions participating in the Gaia Multilateral Agreement.')

    q_tri, = _quoted(T.usgs('triton_fgdc'), 'Grid lines were filled by neighboring pixels.')

    def fg(key):
        f = T.fgdc(key)
        return f, (f'USGS FGDC record {os.path.basename(T.USGS_FILES[key][0])}: <accconst>{f["accconst"][0]}</accconst> '
                   f'<useconst>{f["useconst"][0]}</useconst>')

    def usgs_src(tif, lbl, md5):
        path, sha, size = T.USGS_FILES[tif]
        side = open(T.usgs(md5), encoding='ascii').read().split()[0]
        return (f'USGS Astrogeology public bucket asc-pds-services, {path} ({size:,} bytes, sha256 {sha[:16]}..., md5 '
                f'{side} = the USGS sidecar), with its ISIS label {os.path.basename(T.USGS_FILES[lbl][0])}')

    def geo_adapt(k, how):
        b = B[k]
        s = (f'{how} Area-averaged (every source pixel counted once, nodata excluded) to {b["width"]}x{b["height"]}, '
             f'east-positive, left edge {b["lon_left_deg"]:g} deg ({b["lon_evidence"]}); JPEG quality 85.')
        if b['nodata_fraction'] > 0:
            s += f' {pct(k)} of the pixels had no data: {b["nodata_fill"]}.'
        return s

    blocks = []
    blocks.append({
        'id': 'stellarium-sun-hmi', 'title': 'Sun: SDO HMI continuum map (Stellarium sun.webp)',
        'owner': 'NASA Solar Dynamics Observatory, HMI (data); map by Ruslan Kabatsayev for Stellarium '
                 '(commit 2aa98a95, 2025-09-15)',
        'source': 'Stellarium textures/sun.webp at commit 9910a2f0 (8192x4096 WebP, sha256 a1fc496b...)',
        'url': _raw('sun_webp'), 'licence': 'CC BY-SA 4.0',
        'licence_quote': f'Stellarium CREDITS.md section 4.3o: "{q_sun}"', 'retrieved': R,
        'adaptations': 'Averaged 8x8 in linear light to 1024x512; the intensity is kept and Stellarium\'s uniform '
                       f'warm tint is replaced by the TSIS-1 solar colour (sRGB {C["sun"]["srgb"]}); JPEG quality 85. '
                       'The adapted map data/tex/sun.jpg is shared under CC BY-SA 4.0.',
        'accuracy': 'A generic texture, per its commit message: sunspots from HMI images of 2025-08-07 to 08-31, the '
                    'rest spotless data of 2019-12-15, each image used only in the central 60 % of the disc; limb '
                    'darkening removed; no Carrington registration, so longitudes carry no meaning. The source is '
                    'monochrome HMI 617 nm continuum data; the colour is the measured TSIS-1 colour, not HMI\'s.',
    })
    f, q = fg('mercury_fgdc')
    blocks.append({
        'id': 'usgs-mercury-messenger-2013', 'title': 'Mercury: MESSENGER MDIS global mosaic 250 m (May 2013)',
        'owner': f'NASA MESSENGER mission; mosaic by {f["origin"][0].replace(",", ", ")} (FGDC originator); '
                 'distributed by USGS Astrogeology',
        'source': usgs_src('mercury_tif', 'mercury_lbl', 'mercury_md5'), 'url': _usgs_url('mercury_tif'),
        'licence': 'Public domain (USGS FGDC access constraint; use constraint "Please cite authors")',
        'licence_quote': q + f'; edition "{f["edition"][0]}"', 'retrieved': R,
        'adaptations': geo_adapt('mercury', 'Monochrome 750 nm basemap (NAC and WAC images; polar mosaics by C. Ernst '
                                            'and N. Chabot, per the FGDC abstract).'),
        'accuracy': 'Mixed illumination (shading is part of the mosaic); a lit globe gets mild double shading.',
    })
    f, q = fg('venus_fgdc')
    blocks.append({
        'id': 'usgs-venus-magellan-c3mdir', 'title': 'Venus: Magellan C3-MIDR global radar mosaic 2025 m',
        'owner': 'NASA/JPL Magellan mission; PDS Geosciences Node (FGDC originator); mosaic by USGS Astrogeology',
        'source': usgs_src('venus_tif', 'venus_lbl', 'venus_md5'), 'url': _usgs_url('venus_tif'),
        'licence': 'Public domain (USGS FGDC access constraint)', 'licence_quote': q, 'retrieved': R,
        'adaptations': geo_adapt('venus', 'S-band synthetic-aperture radar backscatter.'),
        'accuracy': 'Radar brightness of the surface under the clouds, not what an eye sees: the visible Venus is a '
                    'nearly featureless cloud deck, and no Venus colour or cloud map could be sourced.',
    })
    blocks.append({
        'id': 'nasa-bmng-200405', 'title': 'Earth: NASA Blue Marble Next Generation, May 2004 (topography and bathymetry)',
        'owner': 'NASA Earth Observatory / NASA Goddard Space Flight Center (Reto Stöckli), from Terra MODIS',
        'source': 'NASAWorldWind/WebWorldWind images/BMNG_world.topo.bathy.200405.3.2048x1024.jpg at commit 5ffe2dfc '
                  '(sha256 7405c39a...), the file WebWorldWind\'s BMNGOneImageLayer drapes on the full sphere',
        'url': _raw('earth_jpg'),
        'licence': 'Public domain (NASA). WebWorldWind carries no licence text for the image itself; KDE Marble labels '
                   'its copy of the same Blue Marble product "NASA / Public Domain", and the Earth Observatory terms '
                   'quoted in Stellarium\'s CREDITS.md make its material freely reusable.',
        'licence_quote': f'KDE Marble data/maps/earth/bluemarble/bluemarble.dgml @600d542e: {q_bm}; Stellarium '
                         f'CREDITS.md (Blue Marble, Reto Stockli): {q_eo}',
        'retrieved': R, 'adaptations': 'None: shipped byte for byte (2048x1024, left edge -180).',
        'accuracy': 'Cloud-free monthly composite; its colours agree with an independent BMNG copy (PyPI basemap-data) '
                    'to a mean 7 DN (research verifier). No clouds are shown: no clean real cloud map was found.',
    })
    blocks.append({
        'id': 'nasa-noaa-citylights-dmsp', 'title': 'Earth at night: Earth\'s City Lights (DMSP-OLS), KDE Marble copy',
        'owner': 'Marc Imhoff (NASA GSFC), Christopher Elvidge (NOAA NGDC), Craig Mayhew and Robert Simmon (NASA GSFC)',
        'source': 'KDE/marble data/maps/earth/citylights/citylights.jpg at commit 600d542e (2700x1350, sha256 c79ca569...)',
        'url': _raw('night_jpg'), 'licence': 'Public domain (as labelled in KDE Marble\'s citylights.dgml)',
        'licence_quote': f'citylights.dgml @600d542e: {q_cl}', 'retrieved': R,
        'adaptations': 'Box-filtered 2700x1350 -> 2048x1024 (PIL BOX), JPEG quality 85. The dgml gives no bounds; the '
                       'left edge -180 is proved by registering the map\'s own land/ocean base against the Blue '
                       'Marble (best shift 0, not mirrored) and by the positions of Tokyo, New York, Moscow, Cairo, '
                       'Paris and Sao Paulo (verify_textures_sky.py).',
        'accuracy': 'DMSP satellite data of about 2000, composited over a dark land and ocean base (not a pure emission '
                    'layer).',
    })
    blocks.append({
        'id': 'stellarium-moon-lroc-albedo', 'title': 'Moon: LROC WAC Hapke-normalised albedo map (Stellarium moon_4k.jpg)',
        'owner': 'NASA LRO / LROC team, Arizona State University (data); map by Ruslan Kabatsayev for Stellarium '
                 '(commit ef231c69, 2026-03-13)',
        'source': 'Stellarium textures/moon_4k.jpg at commit 9910a2f0 (4096x2048, sha256 ad4435c7...)',
        'url': _raw('moon_jpg'), 'licence': 'CC BY-SA 4.0',
        'licence_quote': f'Stellarium CREDITS.md section 4.2: "{q_moon}"', 'retrieved': R,
        'adaptations': 'Averaged 2x2 to 2048x1024, JPEG quality 85. The adapted map data/tex/moon.jpg is shared under '
                       'CC BY-SA 4.0.',
        'accuracy': 'Albedo with shading removed (suits the app\'s own lighting). Disclosed processing that is not '
                    'measurement: brightness x4, polar colour fitted from the equatorial sectors, and colour balanced '
                    'to grey instead of the natural beige. Longitude convention proved by Tycho, Mare Humorum and the '
                    'maria/highlands asymmetry.',
    })
    f, q = fg('mars_fgdc')
    blocks.append({
        'id': 'usgs-mars-viking-color-925m', 'title': 'Mars: Viking Orbiter global colour mosaic 925 m',
        'owner': 'NASA Viking Orbiter; Planetary Data System (FGDC originator); USGS Astrogeology',
        'source': usgs_src('mars_tif', 'mars_lbl', 'mars_md5'), 'url': _usgs_url('mars_tif'),
        'licence': 'Public domain (USGS FGDC access constraint)', 'licence_quote': q, 'retrieved': R,
        'adaptations': geo_adapt('mars', 'About 1000 red- and violet-filter images, Minnaert-normalised and '
                                         'haze-corrected (FGDC abstract).'),
        'accuracy': 'Two filters only: the green channel was synthesised from the red and violet data (FGDC abstract), '
                    'so dark regions look bluish-grey; close to, not exactly, true colour. Olympus Mons, Syrtis Major '
                    'and Hellas checked at their catalogued positions.',
    })
    blocks.append({
        'id': 'cassini-pia07782', 'title': 'Jupiter: Cassini ISS global colour map PIA07782 (December 2000)',
        'owner': 'NASA/JPL/Space Science Institute (Cassini Imaging Science Subsystem); USGS Astrogeology copy',
        'source': 'USGS asc-pds-services wms_basemaps/Jupiter/Jupiter/originals/jupiter_rgb_cyl_www.jpg (4096x2048, '
                  'sha256 0c6fa8e9...), with the annotated original jupiter_from_cassini.tif for the longitude labels',
        'url': _usgs_url('jupiter_jpg'),
        'licence': 'JPL Image Use Policy: any purpose with a credit line. The Space Science Institute is a non-NASA '
                   'co-credit; the policy notes that such third-party material may carry restrictions on commercial use.',
        'licence_quote': 'USGS mapfile maps/jupiter/jupiter_simp_cyl.map: "Image credit by NASA/JPL/Space Science '
                         'Institute."; JPL Image Use Policy (CelestiaContent LICENSES/JPL-image.txt): "' +
                         '" ... "'.join(q_jpl) + '"',
        'retrieved': R,
        'adaptations': 'Averaged 2x2 to 2048x1024, JPEG quality 85. Not flipped: the annotated original labels its x '
                       'axis 180, 150, ... 0, 330, ... 180, i.e. west longitude decreasing to the right, so east '
                       'longitude increases to the right; left edge 180 W (-180 E). The web copy is the same picture '
                       '(correlation 0.999 at zero shift, 0.85 mirrored). The web copy\'s world file puts the left '
                       'edge at longitude 0 instead, 180 deg from the annotation; the annotation is followed.',
        'accuracy': 'A snapshot of 11-12 December 2000 from 36 images in two filters (451 and 750 nm) combined to '
                    'near-natural colour; the poles were poorly observed, and the source map is one flat colour '
                    f'{B["jupiter"]["fill_value"]} over the south polar region ({pct("jupiter")} of the pixels): '
                    'not imaged, not terrain. Features drift in longitude, so the Great '
                    'Red Spot (about 21 S in this map) will not match any other date; the file does not state the '
                    'longitude system.',
    })
    for k, title, extra in (
            ('pluto', 'Pluto: New Horizons LORRI/MVIC global mosaic 300 m (July 2017)',
             'Its label puts the map\'s centre at 180 E (0..360); Sputnik Planitia checked at 175 E, 20 N. '),
            ('charon', 'Charon: New Horizons LORRI/MVIC global mosaic 300 m (July 2017)', '')):
        f, q = fg(f'{k}_fgdc')
        blocks.append({
            'id': f'usgs-{k}-new-horizons-2017', 'title': title,
            'owner': f'{f["origin"][0].replace(",", ", ")} (FGDC originators); distributed by USGS Astrogeology',
            'source': usgs_src(f'{k}_tif', f'{k}_lbl', f'{k}_md5'), 'url': _usgs_url(f'{k}_tif'),
            'licence': 'No licence stated: FGDC access constraint "None", use constraint "Please cite authors"; a NASA '
                       'mission product distributed by USGS. Credited as asked.',
            'licence_quote': q, 'retrieved': R,
            'adaptations': geo_adapt(k, 'Panchromatic LORRI and MVIC images of the 2015 flyby.'),
            'accuracy': extra + 'Resolution is very uneven (sharp on the encounter hemisphere). The flat grey area is '
                        'where New Horizons saw nothing (southern polar night); it is not terrain. Longitudes are in '
                        'the frame the mosaic was made in (nh_targets_v001 / pck00010 per its ISIS label).',
        })
    for k, title, how, extra in (
            ('io', 'Io: Galileo SSI and Voyager 1 global mosaic 1 km', 'Galileo SSI and Voyager 1 images.',
             'Labelled PositiveWest; drawn east-positive (Loki Patera checked at 308.8 W).'),
            ('ganymede', 'Ganymede: Voyager and Galileo SSI global mosaic 1 km', 'Voyager 1/2 and Galileo SSI images.',
             'Labelled PositiveWest; drawn east-positive (Galileo Regio, Tros and Osiris checked).'),
            ('triton', 'Triton: Voyager 2 global mosaic 600 m, orange filter', 'Only the orange-filter band of the '
             'Voyager 2 colour composite (orange, violet and UV shown as RGB, i.e. false colour) is used.',
             'The flat grey north was in darkness during the 1989 flyby: not imaged, not terrain. The producer notes '
             f'(FGDC procedure): "{q_tri}"')):
        if k not in B:
            continue
        f, q = fg(f'{k}_fgdc')
        blocks.append({
            'id': B[k]['source_id'], 'title': title,
            'owner': f'{f["origin"][0].replace(",", ", ")} (FGDC originator); NASA/JPL missions; USGS Astrogeology',
            'source': usgs_src(f'{k}_tif', f'{k}_lbl', f'{k}_md5'), 'url': _usgs_url(f'{k}_tif'),
            'licence': 'Public domain (USGS FGDC access constraint)', 'licence_quote': q, 'retrieved': R,
            'adaptations': geo_adapt(k, how), 'accuracy': extra + ' Grayscale only; 512x256.',
        })
    kc = ', '.join(f'{k.capitalize()} {C[k]["srgb"]}' for k in ('jupiter', 'saturn', 'uranus', 'neptune', 'titan'))
    blocks.append({
        'id': 'karkoschka-1998-spectra', 'title': 'Disk colours: Karkoschka (1998) albedo spectra of Jupiter, Saturn, '
                                                  'Uranus, Neptune and Titan, 300-1050 nm',
        'owner': 'Erich Karkoschka; ESO spectrophotometry of 1995-07-06 to 07-10; NASA Planetary Data System',
        'source': 'PDS3 product 1995LOW.TAB and its label, carried verbatim in OrbitalCommons/starfield '
                  'crates/surfaces/data/planet-spectra at commit 5cbc6620 (sha256 d8071e07... / 6fa49ffa...)',
        'url': _raw('karkoschka_tab'),
        'licence': 'PDS archive data (the label states no licence); the carrying repository is MIT-licensed',
        'licence_quote': '1995LOW.LBL: ' + '; '.join(q_kar_note) + f'; starfield LICENSE: "{q_mit}"', 'retrieved': R,
        'adaptations': 'Each spectrum x TSIS-1 sunlight integrated against the CIE 1931 2-degree colour-matching '
                       'functions (as tabulated in colour-science 0.4.6, BSD-3-Clause), 1 nm steps 360-830 nm, Y = 1 '
                       'for a white reflector, Bradford-adapted from the Sun\'s white to D65, IEC 61966-2-1 sRGB: '
                       f'{kc}.',
        'accuracy': 'Disk-averaged colours of July 1995 (Uranus\'s colour changes with its seasons); Jupiter, Saturn and '
                    'Titan are full-disk albedo at 5.7-6.8 deg phase, Uranus and Neptune geometric albedo. An '
                    'equal-energy illuminant instead of TSIS-1 changes them by at most 3 of 255.',
    })
    blocks.append({
        'id': 'tsis-1-hsrs', 'title': 'Sun\'s colour: TSIS-1 Hybrid Solar Reference Spectrum v2',
        'owner': 'NASA TSIS-1 / LASP (Coddington et al. 2023); 1 nm resampling by OrbitalCommons/starfield',
        'source': 'crates/surfaces/data/solar-spectrum/tsis1_hsrs_v2_1nm.csv in OrbitalCommons/starfield at commit '
                  '5cbc6620 (sha256 c27ca614...); LASP LISIRD itself is not reachable from the build network',
        'url': _raw('tsis_csv'),
        'licence': 'No licence in the file; the carrying repository is MIT-licensed',
        'licence_quote': 'File header: "' + '" / "'.join(q_tsis) + f'"; starfield LICENSE: "{q_mit}"', 'retrieved': R,
        'adaptations': f'Colour of sunlight above the atmosphere: CIE xy {C["sun"]["xy"]}, about {C["sun"]["cct_k_mccamy"]} K '
                       f'(McCamy), sRGB {C["sun"]["srgb"]} with the brightest channel at 255; used for the Sun\'s disc '
                       'and to tint the Sun map. Also the illuminant for the planets\' disk colours.',
        'accuracy': 'Solar-minimum spectrum, 0.3 % archive uncertainty over 460-2365 nm (file header).',
    })

    sky = json.load(open(sky_path, encoding='utf-8'))
    d = sky['dedup']
    blocks.append({
        'id': 'gaia-dr3-hats-counts', 'title': 'Sky backdrop: Gaia DR3 source counts (STScI/MAST HATS point map)',
        'owner': 'European Space Agency (ESA), Gaia Data Processing and Analysis Consortium (DPAC): Gaia Data Release 3. '
                 'HATS catalogue by the LSST Interdisciplinary Network for Collaboration and Computing, hosted by '
                 'STScI/MAST on AWS Open Data.',
        'source': f'point_map.fits (S3 bucket stpubdata, gaia/gaia_dr3/public/hats/gaia, versionId '
                  f'{T.GAIA_FILES["point_map"][1]}, sha256 {T.GAIA_FILES["point_map"][2][:16]}...), and the source_id '
                  'and _healpix_29 columns of partitions Norder=4/Npix=115 and Norder=3/Npix=29 (read by range '
                  'requests at pinned versionIds, content pinned by sha256)',
        'url': f'{T.GAIA}point_map.fits?versionId={T.GAIA_FILES["point_map"][1]}',
        'licence': 'CC BY-NC 3.0 IGO (non-commercial). ESA\'s Gaia licence page could not be read from the build '
                   'network; a web-search summary of cosmos.esa.int/web/gaia-users/license gives CC BY-NC 3.0 IGO, '
                   'and CelestiaContent\'s Gaia-derived data/stars.dat.license states the same. The AWS Open Data '
                   'Registry entry only says "Attribution required".',
        'licence_quote': f'AWS Open Data Registry datasets/mast-gaia-dr3.yaml @00eb3872: "{q_aws[0]}" and "{q_aws[1]}"; '
                         f'CelestiaContent data/stars.dat.license @eab93932: "{q_cel}"; acknowledgement (as quoted in '
                         f'AT-HYG ACKNOWLEDGMENTS.md): "{q_ack}"',
        'retrieved': R,
        'adaptations': f'Two partitions of the MAST copy repeat rows (the same source_id up to 3 times): '
                       + '; '.join(f'{p["partition"]} {p["rows"]:,} rows, {p["distinct_source_id"]:,} distinct'
                                   for p in d['partitions'])
                       + f'. Their {sum(p["order8_pixels_changed"] for p in d["partitions"])} HEALPix pixels were '
                       f'recounted from distinct source_id, giving {d["total_after_fix"]:,} sources. Counts per square '
                       'degree interpolated bilinearly onto a 2048x1024 ICRS equirectangular grid (RA increasing to the '
                       'right), asinh stretch (black 2,500, soft 20,000, white 1,200,000 per deg^2, recorded in '
                       'data/sky/sky.json), grayscale JPEG quality 85. Shared under the same terms (non-commercial).',
        'accuracy': 'Star counts, not surface brightness: the bulge and the Magellanic Clouds are bright, bright stars '
                    'do not stand out, and dust shows as holes. NSIDE 256 (0.23 deg pixels). The shipped 8-bit '
                    'pixels invert (sky.json stretch) to the densities to a median 1.7 %, 99th percentile 11 % '
                    '(verify_textures_sky.py). A global duplicate check of all 2,016 partitions '
                    'was out of reach (8 GB of source_id); ten more suspicious partitions were checked clean by the '
                    'research verifier.',
    })
    path = os.path.join(TOOLS, 'credits', 'textures-sky.json')
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(json.dumps(blocks, ensure_ascii=False, indent=1) + '\n')
    print(f'credits: {path} ({len(blocks)} blocks)')
