/* Finances — Snuggery mini-app.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * SHAPE OF ./data/snapshot.json — the ONLY file that changes between updates.
 * Rewritten by scripts/finances.py (see .github/workflows/refresh-finances.yml).
 * Nothing in this file, index.html or style.css moves when the data changes.
 *
 * All money is a NUMBER in `currency` units, never a string. Positive is money
 * you have or received; negative is money you owe or spent. A credit card
 * balance is therefore negative. Dates are "YYYY-MM-DD" in the snapshot's own
 * `timezone`; timestamps are ISO 8601 with a Z.
 *
 * Every value below is an EXAMPLE — the shape, not anybody's numbers. The
 * snapshot that ships with this app is generated by
 * scripts/make_demo_finances.py and says so on screen.
 *
 * {
 *   "schema": 2,                        // bump only on a breaking change
 *   "generatedAt": "2026-09-21T05:12:03Z",   // REQUIRED. Shown in the header.
 *   "currency": "NOK",
 *   "timezone": "UTC",                  // IANA name; LOCAL_TZ_NAME in the script
 *   "synthetic": true,                  // true => example data, app says so
 *
 *   // One entry per upstream connection. status: "ok" | "stale" | "error"
 *   //   | "derived" (computed here rather than fetched, e.g. the fund units).
 *   // A source that failed must still appear, with status and message set —
 *   // that is how a half-failed refresh shows on screen instead of silently
 *   // dropping an account and making net worth look like it fell.
 *   "sources": [{
 *     "id": "bank", "label": "Bank", "status": "ok",
 *     "fetchedAt": "2026-09-21T05:11:58Z",
 *     "consentExpires": "2027-02-19",   // ISO date or null; PSD2 re-auth deadline
 *     "message": null                   // human-readable reason when not "ok"
 *   }, …],
 *
 *   // id -> display name for every category used below. A category with no
 *   // entry falls back to its own id, so this map is a convenience, not a gate.
 *   "categoryLabels": { "groceries": "Groceries", "income": "Income", … },
 *
 *   // Anything the job wants to say about how it got here — an index it could
 *   // not reach, an asset it could not value. Shown as banners.
 *   "notes": ["House-price index unavailable; the home is held at its anchor", …],
 *
 *   "netWorth": {                       // REQUIRED, `total` must be a number
 *     "total": 2450000.00,              // everything below, added up
 *     "cash": 180000.00,                // sum of positive account balances
 *     "investments": 96000.00,          // funds + employee shares, NOT pension
 *     "funds": 96000.00,                // the fund side of it
 *     "equity": 0.00,                   // the employee-share side of it
 *     "pension": 0.00,                  // counted separately: locked for decades
 *     "assets": 5300000.00,             // property + vehicles + other
 *     "liabilities": -3126000.00,       // negative: cardDebt + loans
 *     "cardDebt": -6000.00,
 *     "loans": -3120000.00,
 *     "change30d": 18422.30,            // null when history is too short
 *     "change365d": 96410.75
 *   },
 *
 *   // Things no bank reports. Each is anchored to a value on a date and moved
 *   // forward by `basis`, which NAMES THE METHOD AND WHAT IT RESOLVED TO — so
 *   // a fallback ("index unavailable — holding the anchor value") never reads
 *   // like the thing that was asked for.
 *   "assets": [{
 *     "id": "home", "name": "Home", "kind": "property",   // property|vehicle|other
 *     "value": 4930000.00, "anchorValue": 4500000, "anchorDate": "2022-03-15",
 *     "basis": "SSB 07221 — Alle boligtyper, Hele landet",
 *     "note": "Example text — a round figure, not a valuation",
 *     "changeSinceAnchor": 430000.00, "change365d": 147620.00,
 *
 *     // OPTIONAL. More than one defensible way to value the same thing — for a
 *     // home, which cut of the price index to follow. The FIRST is the one
 *     // every other number in this file was built from; the app offers the
 *     // rest as a switch and redraws from `history`, which runs day for day
 *     // with `history.days`. Absent => there is nothing to choose.
 *     "variants": [{
 *       "id": "detached", "label": "Detached houses",
 *       "value": 4880000.00, "basis": "SSB 07221 — Eneboliger, Hele landet",
 *       "history": [ … one value per history day … ]
 *     }, …]
 *   }, …],
 *
 *   "loans": [{                          // balances are NEGATIVE
 *     "id": "home-loan", "name": "Home loan", "against": "home",
 *     "balance": -2900000.00, "principal": 3200000, "paidOff": 0.094,
 *     "monthlyPayment": 18453.00, "nominalRate": 0.049,
 *     "termMonths": 300, "kind": "annuity",
 *     "basis": "modelled annuity, 42 of 300 payments made",
 *     "fromBank": false                  // true => the bank reported it, not modelled
 *   }, …],
 *
 *   "accounts": [{                      // REQUIRED array, may be empty
 *     "id": "bank-1", "name": "Everyday account", "source": "bank",
 *     "type": "current",                // current | savings | credit | other
 *     "balance": 48210.55,
 *     "available": 48210.55,            // or null
 *     "mask": "•• 4417",                // never the full account number
 *     "creditLimit": null,              // credit cards only
 *     "dueDate": null,                  // credit cards only, ISO date
 *     "dueAmount": null                 // credit cards only
 *   }, …],
 *
 *   "investments": {                    // omit or null if no funds are tracked
 *     "total": 96000.00, "costBasis": 84000.00, "unrealised": 12000.00,
 *     "monthly": 3000.00,               // size of the standing purchase, or null
 *     "anchoredAt": "2026-06-30",       // last time units were set from the provider
 *     "accruedSince": 8,                // purchases accrued since that anchor
 *     "historyBasis": "market",         // "market" (real NAV history) | "contributions"
 *                                       //   (units move, price held flat) | "mixed"
 *     "funds": [{
 *       "name": "Global index fund", "isin": "XX0000000000",
 *       "units": 412.8834, "nav": 232.51, "navDate": "2026-09-18",
 *       "value": 96000.00, "costBasis": 84000.00, "allocation": 1.0,
 *       "navSource": "yahoo"            // or "stale" / "manual" / "inline"
 *     }, …],
 *     "series": {                       // optional; drives the growth chart
 *       "days": ["2025-09-21", …], "value": [ … ], "contributed": [ … ]
 *     }
 *   },
 *
 *   // Employee shares (a share-plan administrator such as the one your
 *   // employer uses). The administrator is NOT read — its API is a partner
 *   // integration sold to an employer, and a share plan is not a payment
 *   // account so PSD2 misses it too. Share counts are copied out once; vesting
 *   // is then just the calendar, and the price and FX rate are public.
 *   // null when no share plan is configured, as in the example data.
 *   "equity": {
 *     "provider": "Share plan", "symbol": "XXXX", "currency": "USD",
 *     "price": 58.42, "priceDate": "2026-09-18", "priceSource": "yahoo",
 *     "fxRate": 10.284, "fxDate": "2026-09-18", "fxSource": "norges-bank",
 *     "vestedShares": 418, "unvestedShares": 264,
 *     "vested": 251131.00,              // vested shares, in the snapshot currency
 *     "unvested": 158609.00,            // gross, before tax at vest
 *     "unvestedAfterTax": 84063.00, "unvestedTaxRate": 0.47,
 *     "includeUnvested": false,         // whether net worth counts the unvested
 *     "counted": 251131.00,             // what netWorth.equity actually uses
 *     "costBasis": 41200.00,            // 0 for granted shares; real for ESPP
 *     "historyBasis": "market",         // "market" | "partial" | "flat"
 *     "grants": [{ "id": "rsu-2024", "label": "RSU 2024", "kind": "rsu",
 *                  "strike": null, "underWater": false,
 *                  "vestedShares": 192, "unvestedShares": 96,
 *                  "vested": 115352.00, "unvested": 57676.00,
 *                  "costBasis": 0, "nextVest": "2027-03-15" }, …],
 *     "upcoming": [{ "date": "2027-03-15", "shares": 96,
 *                    "label": "RSU 2024", "value": 57676.00 }, …],
 *     "error": null                     // set => these are NOT in net worth
 *   },
 *
 *   // Pension. Kept out of `investments` on purpose: it is counted in net
 *   // worth but cannot be touched for decades, and folding it in would flatter
 *   // every other figure on screen. Two shapes, and `basis` says which: a
 *   // personal pension is paid from your own account, so its purchases are in
 *   // the bank feed and its units accrue like any fund holding; an employer's
 *   // account never touches your bank and holds share classes nothing public
 *   // prices, so it is anchored to a value and carried by a proxy fund — an
 *   // estimate, which is why `anchoredAt` is on screen next to it.
 *   // null when no pension is configured, as in the example data.
 *   "pension": {
 *     "provider": "Pension", "total": 512000.00, "costBasis": 40000.00,
 *     "counted": 512000.00,             // what netWorth.pension uses
 *     "includeInNetWorth": true,        // false => shown, not counted
 *     "accounts": [{
 *       "id": "personal", "label": "Personal pension", "kind": "personal",
 *       "value": 66500.00, "costBasis": 40000.00,
 *       "anchoredAt": "2026-06-30", "accruedSince": 0,
 *       "basis": "units held, priced at published NAV",
 *       "funds": [ … same shape as investments.funds … ]
 *     }, …],
 *     "notes": [ … anything that could not be priced … ]
 *   },
 *
 *   "history": {                        // REQUIRED. Daily, ascending, no gaps.
 *     "days":       ["2025-08-13", …],  // parallel arrays, all the same length
 *     "netWorth":   [ … ],              // = cash + investments + pension
 *                                       //     + assets + liabilities
 *     "cash":       [ … ],
 *     "investments":[ … ],
 *     "pension":    [ … ],              // 0s when no pension is tracked
 *     "assets":     [ … ],
 *     "liabilities":[ … ]               // negative
 *   },
 *   // Recomputed from scratch every run, not appended to: every component
 *   // except cash is a function of the date, so fixing a wrong anchor fixes
 *   // the past too. It reaches back only as far as the transactions do.
 *
 *   "cashflow": {                       // optional
 *     "months": ["2025-10", …],         // YYYY-MM, ascending, up to 24
 *     "in":  [ … ],                     // positive
 *     "out": [ … ]                      // positive magnitudes, not negative
 *   },
 *
 *   "spending": {                       // optional
 *     "windowDays": 30, "from": "2026-08-22", "to": "2026-09-21",
 *     "total": 28410.50, "previousTotal": 31220.00,
 *     "categories": [{ "id": "groceries", "label": "Groceries",
 *                      "amount": 8410.50, "count": 24, "previous": 9100.00 }, …],
 *     "merchants":  [{ "label": "Grocery Store", "amount": 3980.00, "count": 11 }, …]
 *   },
 *
 *   "recurring": [{                     // optional
 *     "label": "Monthly Fund Purchase", "amount": -3000.00, "cadence": "monthly",
 *     "lastSeen": "2026-09-05", "nextExpected": "2026-10-05"
 *   }, …],
 *
 *   "transactions": [{                  // optional, newest first, capped ~300
 *     "date": "2026-09-18", "text": "GROCERY STORE", "amount": -412.50,
 *     "account": "Everyday account", "source": "bank", "category": "groceries"
 *   }, …],
 *
 *   // The table Snuggery's "Ask About This Data" reads, and the only key it
 *   // reads. Flat rows, plain keys, numbers or short strings, a couple of
 *   // hundred at most — the figures a person would ask about in words. It is
 *   // for reading, never for drawing: this app does not touch it.
 *   "ask": [
 *     { "row": "networth", "date": "2026-09-21", "netWorth": 2450000,
 *       "cash": 180000, "investments": 96000, "pension": 0,
 *       "assets": 5300000, "liabilities": -3126000,
 *       "change30d": 18422.3, "change365d": 96410.75 },
 *     { "row": "account", "name": "Everyday account", "kind": "current",
 *       "balance": 48210.55, "source": "Bank" },
 *     { "row": "owned", "name": "Home", "kind": "property", "value": 4930000,
 *       "anchorValue": 4500000, "anchorDate": "2022-03-15",
 *       "change365d": 147620, "basis": "SSB 07221 — Alle boligtyper, Hele landet" },
 *     { "row": "loan", "name": "Home loan", "balance": -2900000,
 *       "monthlyPayment": 18453, "ratePct": 4.9, "paidOffPct": 9.4 },
 *     { "row": "month", "month": "2026-08", "in": 52400, "out": 41230,
 *       "net": 11170 },
 *     { "row": "category", "category": "Groceries", "windowDays": 30,
 *       "amount": 8410.5, "count": 24, "previousAmount": 9100 },
 *     { "row": "merchant", "merchant": "Grocery Store", "windowDays": 30,
 *       "amount": 3980, "count": 11 },
 *     { "row": "recurring", "label": "Monthly Fund Purchase", "amount": -3000,
 *       "cadence": "monthly", "nextExpected": "2026-10-05" },
 *     { "row": "fund", "name": "Global index fund", "value": 96000,
 *       "costBasis": 84000, "gain": 12000, "navDate": "2026-09-18" }
 *   ]
 * }
 *
 * Adding an account, a fund or a category needs no change here — every list
 * builds itself from whatever the file contains. A source that stops appearing
 * simply vanishes from the screen until it comes back.
 * ───────────────────────────────────────────────────────────────────────────── */

const DATA_URL = './data/snapshot.json';
const STORE_TAB = 'fin.tab';
const STORE_RANGE = 'fin.range';
const STORE_BASIS = 'fin.basis';

/* Categorical slots, fixed order, never cycled — read from the stylesheet so
   light and dark each get their own validated step. Used only where identity
   is the job (which fund a stacked segment is). Amount-across-categories is one
   series and therefore one colour. */
const SERIES = n => `var(--series-${n})`;

let snap = null;
let baseSnap = null;        // as it arrived; `snap` may be re-based onto a variant
let range = +(localStorage.getItem(STORE_RANGE) || 90);
let txQuery = '';
let txShown = 100;          // 300 rows at once is a 50 000-pixel page

/* Which valuation basis is chosen per asset, {assetId: variantId}. Survives a
   reload, because a house valued two ways is a preference, not a session. */
let basisChoice = (() => {
  try { return JSON.parse(localStorage.getItem(STORE_BASIS) || '{}') || {}; }
  catch { return {}; }
})();

const $ = id => document.getElementById(id);
const el = (tag, cls, txt) => {
  const n = document.createElement(tag);
  if (cls) n.className = cls;
  if (txt != null) n.textContent = txt;
  return n;
};

/** Swap a whole pane for one explanatory card, reversibly: render() runs again
 *  on every visibility change, so a pane emptied by destroying its nodes would
 *  never come back when the data returned. */
function paneEmpty(paneId, msg) {
  const pane = $(paneId);
  let box = pane.querySelector(':scope > .emptycard');
  if (!box) {
    box = el('div', 'card emptycard');
    box.appendChild(el('div', 'empty'));
    pane.insertBefore(box, pane.firstChild);
  }
  box.firstChild.textContent = msg;
  box.hidden = false;
  for (const c of pane.children) if (c !== box) c.hidden = true;
  return false;
}

/** The other half: show the real cards again and drop the explanation. */
function paneFilled(paneId) {
  const pane = $(paneId);
  const box = pane.querySelector(':scope > .emptycard');
  if (box) box.hidden = true;
  for (const c of pane.children) if (c !== box) c.hidden = false;
  return true;
}

/* ── Formatting ──────────────────────────────────────────────────────── */

const nf = (n, d = 0) => Number(n).toLocaleString('nb-NO',
  { minimumFractionDigits: d, maximumFractionDigits: d });

/* Everything that reaches innerHTML goes through this. The only innerHTML in
   this app is the chart tooltip, and the only values in it are formatted dates
   and formatted numbers — but data/snapshot.json is a file a Shortcut writes,
   so "it can only be a date" is an assumption about the file rather than a
   property of it. Escaping costs nothing and removes the assumption. */
const esc = (v) => String(v)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;').replace(/'/g, '&#39;');

const kr = (n, d = 0) => (n == null || !isFinite(n)) ? '—' : `${nf(n, d)} kr`;

const krSigned = (n, d = 0) =>
  (n == null || !isFinite(n)) ? '—' : `${n > 0 ? '+' : ''}${nf(n, d)} kr`;

/** Short form for a chart axis, where the tick has to fit. `step` is the gap
 *  between ticks: the decimals come from it, so every tick on one axis is
 *  written the same way rather than 5,0m sitting next to 10m. */
function krAxis(n, step) {
  if (n === 0) return '0';          // "0m" is not a quantity anybody writes
  const gap = Math.abs(step || n) || 1;
  if (gap >= 1e6) return `${nf(n / 1e6, gap >= 1e6 ? 0 : 1)}m`;
  if (Math.abs(n) >= 1e6) return `${nf(n / 1e6, 1)}m`;
  if (gap >= 1e3) return `${nf(n / 1e3, 0)}k`;
  if (Math.abs(n) >= 1e4) return `${nf(n / 1e3, 0)}k`;
  if (Math.abs(n) >= 1e3) return `${nf(n / 1e3, 1)}k`;
  return nf(n, 0);
}

const pct = (n, d = 1) => (n == null || !isFinite(n)) ? '—' : `${nf(n * 100, d)} %`;

function dayLabel(iso) {
  const d = new Date(`${iso}T12:00:00Z`);
  return d.toLocaleDateString('en-GB', { day: 'numeric', month: 'short' });
}

function fullDay(iso) {
  const d = new Date(`${iso}T12:00:00Z`);
  return d.toLocaleDateString('en-GB', { weekday: 'short', day: 'numeric', month: 'short', year: 'numeric' });
}

function monthYear(iso) {
  const d = new Date(`${iso}T12:00:00Z`);
  return d.toLocaleDateString('en-GB', { month: 'short', year: 'numeric' });
}

function monthLabel(ym) {
  const d = new Date(`${ym}-01T12:00:00Z`);
  return d.toLocaleDateString('en-GB', { month: 'short' });
}

function monthFull(ym) {
  const d = new Date(`${ym}-01T12:00:00Z`);
  return d.toLocaleDateString('en-GB', { month: 'long', year: 'numeric' });
}

function ago(iso) {
  const t = Date.parse(iso);
  if (!isFinite(t)) return 'at an unknown time';
  const mins = Math.round((Date.now() - t) / 60000);
  if (mins < 2) return 'just now';
  if (mins < 60) return `${mins} min ago`;
  const hrs = Math.round(mins / 60);
  if (hrs < 24) return `${hrs} ${hrs === 1 ? 'hour' : 'hours'} ago`;
  const days = Math.round(hrs / 24);
  return `${days} ${days === 1 ? 'day' : 'days'} ago`;
}

const daysBetween = (a, b) => Math.round((Date.parse(b) - Date.parse(a)) / 86400000);

/* ── Loading and validation ──────────────────────────────────────────── */

/* An expired credential does not return a network error — it returns an error
   page that is perfectly valid JSON, and whatever delivers the file writes it
   straight over the good data. So parsing is not the test: the test is whether
   the fields this app actually reads are present and the right type. */
function validate(d) {
  const bad = m => ({ ok: false, why: m });
  if (d === null || typeof d !== 'object' || Array.isArray(d)) return bad('The file is not a JSON object.');
  if (typeof d.generatedAt !== 'string' || !isFinite(Date.parse(d.generatedAt)))
    return bad('`generatedAt` is missing or is not an ISO 8601 timestamp.');
  if (!d.netWorth || typeof d.netWorth.total !== 'number' || !isFinite(d.netWorth.total))
    return bad('`netWorth.total` is missing or is not a number.');
  if (!Array.isArray(d.accounts)) return bad('`accounts` is missing or is not an array.');

  const h = d.history;
  if (!h || !Array.isArray(h.days) || !Array.isArray(h.netWorth))
    return bad('`history.days` / `history.netWorth` are missing or are not arrays.');
  if (h.days.length !== h.netWorth.length)
    return bad(`\`history\` arrays disagree: ${h.days.length} days against ${h.netWorth.length} values.`);
  if (!h.days.length) return bad('`history` is empty — there is nothing to plot.');
  if (h.netWorth.some(v => typeof v !== 'number' || !isFinite(v)))
    return bad('`history.netWorth` holds something that is not a number.');

  if (d.accounts.some(a => !a || typeof a.balance !== 'number' || !isFinite(a.balance)))
    return bad('An entry in `accounts` has no numeric `balance`.');

  return { ok: true };
}

function showError(title, detail) {
  const box = $('error');
  box.hidden = false;
  box.innerHTML = '';
  box.appendChild(el('strong', null, title));
  box.appendChild(el('div', null, detail));
  const hint = el('div');
  hint.style.marginTop = '8px';
  hint.style.fontSize = '12.5px';
  hint.style.opacity = '.85';
  hint.textContent = 'Nothing below is drawn from this file, so none of it is a stale number pretending to be fresh. '
    + 'A private repository answers 404 rather than 401 when the token is wrong — check the token before the address.';
  box.appendChild(hint);
  $('main').hidden = true;
  $('footer').hidden = true;
  $('freshness').textContent = 'Data unavailable';
}

async function load() {
  let text;
  try {
    const res = await fetch(`${DATA_URL}?t=${Date.now()}`, { cache: 'no-store' });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    text = await res.text();
  } catch (e) {
    showError('Could not read data/snapshot.json', `The file did not load: ${e.message}.`);
    return;
  }

  let parsed;
  try {
    parsed = JSON.parse(text);
  } catch (e) {
    showError('data/snapshot.json will not parse',
      `It is not valid JSON: ${e.message}. It begins: ${JSON.stringify(text.slice(0, 120))}`);
    return;
  }

  const v = validate(parsed);
  if (!v.ok) {
    showError('data/snapshot.json is not the shape this app expects', v.why);
    return;
  }

  // A reload is a re-render IN PLACE. The open tab survives because nothing
  // here calls showTab(), and the scroll position is put back by hand: the
  // panes are rebuilt from scratch, and a document that is briefly shorter
  // than it was clamps the scroll to its new bottom. Only on a reload — the
  // first load should start at the top.
  const wasShowing = baseSnap !== null && baseSnap !== undefined;
  const keepScroll = wasShowing ? window.scrollY : 0;

  baseSnap = parsed;
  snap = rebase(parsed);
  $('error').hidden = true;
  $('main').hidden = false;
  $('footer').hidden = false;
  render();

  if (wasShowing && keepScroll) {
    // After layout, or the page may not yet be tall enough to scroll back to.
    requestAnimationFrame(() => window.scrollTo({ top: keepScroll }));
  }
}

/* ── Valuation basis ──────────────────────────────────────────────────────
   An asset may offer more than one honest way to value it — for the house,
   which cut of SSB's index to follow. The file is built on the first one, so
   choosing another is a DELTA against that: apply it to the asset, to net
   worth, and to every day of the history, and then let the ordinary render
   redraw. Nothing here invents a number; the refresh job computed each
   variant's whole line and this only picks which one to show. */

function rebase(base) {
  const ids = Object.keys(basisChoice);
  if (!base || !ids.length || !Array.isArray(base.assets)) return base;

  const out = {
    ...base,
    assets: base.assets.map(a => ({ ...a })),
    netWorth: { ...base.netWorth },
    history: { ...base.history },
  };

  const days = (base.history && base.history.days) || [];
  let delta = null;                       // per-day, built only if something moves
  let deltaNow = 0;

  for (const a of out.assets) {
    const want = basisChoice[a.id];
    const vs = Array.isArray(a.variants) ? a.variants : null;
    if (!want || !vs || !vs.length) continue;
    const pick = vs.find(v => v.id === want);
    const built = vs[0];
    if (!pick || pick === built) continue;

    deltaNow += (pick.value || 0) - (built.value || 0);
    a.value = pick.value;
    a.basis = pick.basis;
    a.changeSinceAnchor = round2(pick.value - (a.anchorValue || 0));

    const ph = pick.history, bh = built.history;
    if (Array.isArray(ph) && Array.isArray(bh) &&
        ph.length === bh.length && ph.length === days.length) {
      if (!delta) delta = new Array(days.length).fill(0);
      for (let i = 0; i < ph.length; i++) delta[i] += ph[i] - bh[i];
      const back = ph.length - 1 - 365;
      a.change365d = back >= 0 ? round2(ph[ph.length - 1] - ph[back]) : a.change365d;
    }
  }

  if (!deltaNow && !delta) return base;

  out.netWorth.assets = round2((base.netWorth.assets || 0) + deltaNow);
  out.netWorth.total = round2((base.netWorth.total || 0) + deltaNow);

  if (delta) {
    out.history = { ...base.history };
    for (const key of ['netWorth', 'assets']) {
      const src = base.history[key];
      if (Array.isArray(src) && src.length === delta.length)
        out.history[key] = src.map((v, i) => round2(v + delta[i]));
    }
    // The headline changes are differences between two days of that same line,
    // so they move by the difference between the two deltas, not by deltaNow.
    for (const [key, back] of [['change30d', 30], ['change365d', 365]]) {
      const at = shiftIndex(days, back);
      if (at != null && typeof base.netWorth[key] === 'number')
        out.netWorth[key] = round2(base.netWorth[key]
          + (delta[delta.length - 1] - delta[at]));
    }
  }
  return out;
}

const round2 = n => Math.round(n * 100) / 100;

/** Index of the last day at or before `back` days before the newest one —
    the same rule the refresh job uses, so the two agree. */
function shiftIndex(days, back) {
  if (!days.length) return null;
  const target = Date.parse(days[days.length - 1]) - back * 86400000;
  for (let i = days.length - 1; i >= 0; i--)
    if (Date.parse(days[i]) <= target) return i;
  return null;
}

function chooseBasis(assetId, variantId, isDefault) {
  if (isDefault) delete basisChoice[assetId];
  else basisChoice[assetId] = variantId;
  try { localStorage.setItem(STORE_BASIS, JSON.stringify(basisChoice)); } catch { /* private mode */ }
  snap = rebase(baseSnap);
  render();
}

/* ── Render ──────────────────────────────────────────────────────────── */

function render() {
  renderHeader();
  renderSources();
  renderOverview();
  renderOwned();
  renderSpending();
  renderFlow();
  renderSavings();
  renderTxns();
}

function renderHeader() {
  // The clock time, not "3 hours ago": this job runs once a day, and the one
  // thing a person wants from a header is whether they are looking at today.
  // The date is added the moment it is not today, because "07:20" on its own
  // is the most confident way to show last week's numbers.
  const when = new Date(snap.generatedAt);
  const el0 = $('freshness');
  let stamp;
  if (!isFinite(when.getTime())) {
    stamp = 'Updated at an unknown time';
  } else {
    const time = when.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' });
    const sameDay = when.toDateString() === new Date().toDateString();
    stamp = sameDay
      ? `Updated ${time}`
      : `Updated ${when.toLocaleDateString('en-GB', { weekday: 'short', day: 'numeric', month: 'short' })} ${time}`;
  }
  const parts = [stamp];
  if (snap.synthetic) parts.push('example data');
  el0.textContent = parts.join(' · ');
  // A daily job that has not run for 30 hours has missed one. Say so in the
  // header's own colour rather than leaving yesterday to pass as today.
  const hours = isFinite(when.getTime()) ? (Date.now() - when.getTime()) / 3600000 : Infinity;
  el0.classList.toggle('stale', hours > 30);
  el0.title = isFinite(when.getTime())
    ? `${when.toLocaleString('en-GB')} — ${ago(snap.generatedAt)}`
    : snap.generatedAt;
}

function renderSources() {
  const wrap = $('sourcebanners');
  wrap.innerHTML = '';
  const srcs = Array.isArray(snap.sources) ? snap.sources : [];

  if (snap.synthetic) {
    const b = el('div', 'banner warn');
    b.appendChild(el('span', 'dot'));
    b.appendChild(el('span', null,
      'These are example numbers shipped with the app. They will be replaced the first time the refresh job runs against your banks.'));
    wrap.appendChild(b);
  }

  for (const note of (Array.isArray(snap.notes) ? snap.notes : [])) {
    const b = el('div', 'banner warn');
    b.appendChild(el('span', 'dot'));
    b.appendChild(el('span', null, String(note)));
    wrap.appendChild(b);
  }

  for (const s of srcs) {
    if (s.status === 'ok' || s.status === 'derived') {
      // Consent that is about to lapse is the one thing worth saying early:
      // once it does, the feed goes quiet rather than loud.
      const days = s.consentExpires ? daysBetween(new Date().toISOString().slice(0, 10), s.consentExpires) : null;
      if (days != null && days <= 21) {
        const b = el('div', 'banner warn');
        b.appendChild(el('span', 'dot'));
        b.appendChild(el('span', null, days < 0
          ? `${s.label} access has expired. Re-authorise with BankID to start the feed again.`
          : `${s.label} access expires in ${days} ${days === 1 ? 'day' : 'days'} — re-authorise with BankID before then.`));
        wrap.appendChild(b);
      }
      continue;
    }
    const b = el('div', s.status === 'error' ? 'banner bad' : 'banner warn');
    b.appendChild(el('span', 'dot'));
    b.appendChild(el('span', null,
      `${s.label}: ${s.message || (s.status === 'error' ? 'the last refresh failed' : 'the numbers are older than the rest')}`
      + (s.fetchedAt ? ` Last good read ${ago(s.fetchedAt)}.` : '')));
    wrap.appendChild(b);
  }

  const foot = srcs.map(s => {
    const when = s.fetchedAt ? ago(s.fetchedAt) : 'never';
    return `${s.label} — ${s.status}, read ${when}`;
  });
  $('foot-sources').textContent = foot.length
    ? `Sources: ${foot.join('. ')}.`
    : 'No sources declared in the snapshot.';
}

/* ── Overview ────────────────────────────────────────────────────────── */

function renderOverview() {
  const n = snap.netWorth;
  $('nw-value').textContent = kr(n.total);

  const d = $('nw-delta');
  d.innerHTML = '';
  if (typeof n.change30d === 'number' && isFinite(n.change30d)) {
    const b = el('b', n.change30d >= 0 ? 'pos' : 'neg', krSigned(n.change30d));
    d.append(b, document.createTextNode(' in 30 days'));
    if (typeof n.change365d === 'number' && isFinite(n.change365d)) {
      d.append(document.createTextNode(' · '));
      d.append(el('b', n.change365d >= 0 ? 'pos' : 'neg', krSigned(n.change365d)));
      d.append(document.createTextNode(' in a year'));
    }
  } else {
    d.textContent = 'Not enough history yet to show a change.';
  }

  drawMix(n);
  drawNetWorth();
  document.querySelectorAll('#nw-range button').forEach(b =>
    b.classList.toggle('is-active', +b.dataset.days === range));

  // Accounts, heaviest first, with credit cards last because they read as debt.
  const rows = $('accounts');
  rows.innerHTML = '';
  const accs = [...snap.accounts].sort((a, b) =>
    (a.type === 'credit') - (b.type === 'credit') || b.balance - a.balance);

  if (!accs.length) rows.appendChild(el('div', 'empty', 'No accounts in this snapshot.'));

  for (const a of accs) {
    const r = el('div', 'row');
    const main = el('div', 'main');
    main.appendChild(el('div', 'nm', a.name || 'Account'));
    const bits = [a.mask, sourceLabel(a.source), TYPE_LABEL[a.type] || a.type].filter(Boolean);
    main.appendChild(el('div', 'meta', bits.join(' · ')));
    r.appendChild(main);

    const amt = el('div', 'amount' + (a.balance < 0 ? ' neg' : ''), kr(a.balance));
    if (typeof a.available === 'number' && isFinite(a.available) && Math.abs(a.available - a.balance) > 0.5)
      amt.appendChild(el('span', 'sm', `${kr(a.available)} available`));
    r.appendChild(amt);
    rows.appendChild(r);
  }

  // The card bill gets its own block: it is the one number with a deadline.
  const card = snap.accounts.find(a => a.type === 'credit' && a.dueDate);
  const host = $('card-bill');
  $('card-bill-card').hidden = !card;
  if (card) {
    host.innerHTML = '';
    const r = el('div', 'row');
    const main = el('div', 'main');
    main.appendChild(el('div', 'nm', card.name));
    const left = daysBetween(new Date().toISOString().slice(0, 10), card.dueDate);
    main.appendChild(el('div', 'meta',
      `Due ${fullDay(card.dueDate)} · ${left < 0 ? `${-left} days ago` : left === 0 ? 'today' : `in ${left} days`}`));
    r.appendChild(main);
    const amt = el('div', 'amount neg', kr(Math.abs(card.dueAmount ?? card.balance)));
    if (typeof card.creditLimit === 'number' && card.creditLimit > 0)
      amt.appendChild(el('span', 'sm', `${pct(Math.abs(card.balance) / card.creditLimit, 0)} of limit`));
    r.appendChild(amt);
    host.appendChild(r);
  }
}

/** What the total is made of. A stacked bar rather than a row of splits: five
 *  components will not fit as columns at phone width, and the shares are the
 *  point. Debt is not a slice of it — it is drawn underneath, as its own row. */
function drawMix(n) {
  const parts = [
    { label: 'Cash', value: n.cash || 0, color: SERIES(1) },
    { label: 'Invested', value: n.investments || 0, color: SERIES(3) },
    // Pension is separate from what you have invested, because you cannot
    // reach it for decades — folding it in would flatter every other figure.
    { label: 'Pension', value: n.pension || 0, color: SERIES(2) },
    { label: 'Property & things', value: n.assets || 0, color: SERIES(4) },
  ].filter(p => p.value > 0);

  const svg = $('nw-mix');
  svg.innerHTML = '';
  const gross = parts.reduce((a, p) => a + p.value, 0);
  const W = 320, H = 34, GAP = 2, h = 20;

  if (!gross) {
    $('nw-mixlegend').innerHTML = '';
  } else {
    let x = 0;
    for (const p of parts) {
      const w = Math.max(2, (p.value / gross) * (W - GAP * (parts.length - 1)));
      svg.appendChild(svgEl('rect', {
        x: x.toFixed(2), y: 0, width: w.toFixed(2), height: h, rx: 4, fill: p.color
      }));
      if (w > 44) {
        const t = svgEl('text', { x: (x + w / 2).toFixed(2), y: h + 12, 'text-anchor': 'middle', class: 'dlabel' });
        t.textContent = pct(p.value / gross, 0);
        svg.appendChild(t);
      }
      x += w + GAP;
    }
    const lg = $('nw-mixlegend');
    lg.innerHTML = '';
    for (const p of parts) lg.appendChild(legendItem(p.color, p.label, kr(p.value)));
  }

  // Debt gets its own line because subtracting it is the whole point, and a
  // slice in the same bar would read as something you have.
  const row = $('nw-debtrow');
  row.innerHTML = '';
  const owed = n.liabilities || 0;
  if (owed) {
    const r = el('div', 'row');
    const main = el('div', 'main');
    main.appendChild(el('div', 'nm', 'Less what you owe'));
    const bits = [];
    if (n.loans) bits.push(`${kr(Math.abs(n.loans))} in loans`);
    if (n.cardDebt) bits.push(`${kr(Math.abs(n.cardDebt))} on the card`);
    // This one line is a breakdown, not a subtitle — let it wrap rather than
    // elide the half that says what the rest of the debt is.
    const meta = el('div', 'meta wrap', bits.join(' · '));
    main.appendChild(meta);
    r.append(main, el('div', 'amount neg', kr(owed)));
    row.appendChild(r);
  }
}

const TYPE_LABEL = { current: 'Current', savings: 'Savings', credit: 'Credit card', other: 'Account' };

function catLabel(id) {
  const m = snap.categoryLabels;
  return (m && typeof m[id] === 'string') ? m[id] : (id || '');
}

function sourceLabel(id) {
  const s = (snap.sources || []).find(x => x.id === id);
  return s ? s.label : id;
}

/* ── Chart helpers ───────────────────────────────────────────────────── */

const SVGNS = 'http://www.w3.org/2000/svg';

function svgEl(name, attrs) {
  const n = document.createElementNS(SVGNS, name);
  for (const k in attrs) if (attrs[k] != null) n.setAttribute(k, attrs[k]);
  return n;
}

/** Ticks that land on round money, so the grid reads as money and not as pixels. */
function niceTicks(lo, hi, count = 4, padTop = false) {
  if (!(hi > lo)) { const p = Math.abs(hi) * 0.1 || 1; lo = hi - p; hi = hi + p; }
  const raw = (hi - lo) / count;
  const mag = Math.pow(10, Math.floor(Math.log10(raw)));
  const step = [1, 2, 2.5, 5, 10].map(m => m * mag).find(s => s >= raw) || 10 * mag;
  const out = [];
  const first = Math.floor(lo / step) * step;
  const last = padTop ? Math.ceil(hi / step) * step : Math.floor(hi / step) * step;
  for (let t = first; t <= last + step * 0.001; t += step) out.push(t);
  if (!out.length) out.push(first);
  out.step = step;
  return out;
}

/* ── Net worth chart ─────────────────────────────────────────────────── */

const NW = { x: [], y: [], days: [], vals: [] };

function drawNetWorth() {
  const svg = $('nw-chart');
  svg.innerHTML = '';
  const h = snap.history;
  const total = h.days.length;
  const n = range > 0 ? Math.min(range, total) : total;
  const days = h.days.slice(total - n);
  const vals = h.netWorth.slice(total - n);

  const W = 320, H = 150, L = 42, R = 6, T = 10, B = 20;
  const iw = W - L - R, ih = H - T - B;

  let lo = Math.min(...vals), hi = Math.max(...vals);
  if (lo === hi) { lo -= Math.abs(lo) * 0.02 || 1; hi += Math.abs(hi) * 0.02 || 1; }
  const ticks = niceTicks(lo, hi, 4);
  lo = Math.min(lo, ticks[0]); hi = Math.max(hi, ticks[ticks.length - 1]);

  const X = i => L + (n === 1 ? iw / 2 : (i / (n - 1)) * iw);
  const Y = v => T + ih - ((v - lo) / (hi - lo)) * ih;

  for (const t of ticks) {
    svg.appendChild(svgEl('line', { class: 'grid', x1: L, x2: W - R, y1: Y(t).toFixed(2), y2: Y(t).toFixed(2) }));
    const tx = svgEl('text', { x: L - 6, y: (Y(t) + 3.4).toFixed(2), 'text-anchor': 'end' });
    tx.textContent = krAxis(t, ticks.step);
    svg.appendChild(tx);
  }

  const line = vals.map((v, i) => `${X(i).toFixed(2)},${Y(v).toFixed(2)}`).join(' ');

  const grad = svgEl('linearGradient', { id: 'nwfill', x1: 0, y1: 0, x2: 0, y2: 1 });
  grad.appendChild(svgEl('stop', { offset: '0%', 'stop-color': SERIES(1), 'stop-opacity': .22 }));
  grad.appendChild(svgEl('stop', { offset: '100%', 'stop-color': SERIES(1), 'stop-opacity': 0 }));
  const defs = svgEl('defs'); defs.appendChild(grad); svg.appendChild(defs);

  svg.appendChild(svgEl('polygon', {
    points: `${L},${T + ih} ${line} ${X(n - 1).toFixed(2)},${T + ih}`, fill: 'url(#nwfill)'
  }));
  svg.appendChild(svgEl('polyline', {
    points: line, fill: 'none', stroke: SERIES(1), 'stroke-width': 2,
    'stroke-linejoin': 'round', 'stroke-linecap': 'round'
  }));

  // Only the endpoint is labelled — a number on every point goes unread.
  const last = vals[vals.length - 1];
  svg.appendChild(svgEl('circle', {
    cx: X(n - 1).toFixed(2), cy: Y(last).toFixed(2), r: 3.4,
    fill: SERIES(1), stroke: 'var(--surface-1)', 'stroke-width': 2
  }));

  const firstLbl = svgEl('text', { x: L, y: H - 5 }); firstLbl.textContent = dayLabel(days[0]);
  const lastLbl = svgEl('text', { x: W - R, y: H - 5, 'text-anchor': 'end' }); lastLbl.textContent = dayLabel(days[n - 1]);
  svg.append(firstLbl, lastLbl);

  const cross = svgEl('line', { class: 'axis', y1: T, y2: T + ih, opacity: 0, id: 'nw-cross' });
  const dot = svgEl('circle', { r: 4, fill: SERIES(1), stroke: 'var(--surface-1)', 'stroke-width': 2, opacity: 0, id: 'nw-dot' });
  svg.append(cross, dot);

  NW.days = days; NW.vals = vals;
  NW.geom = { X, Y, L, R, W, n };
  attachHover(svg, $('nw-tip'), (frac) => {
    const i = Math.max(0, Math.min(n - 1, Math.round(frac * (n - 1))));
    cross.setAttribute('x1', X(i)); cross.setAttribute('x2', X(i)); cross.setAttribute('opacity', 1);
    dot.setAttribute('cx', X(i)); dot.setAttribute('cy', Y(vals[i])); dot.setAttribute('opacity', 1);
    return { x: X(i) / W, y: Y(vals[i]) / H,
      html: `<div class="t">${esc(fullDay(days[i]))}</div><div class="v">${esc(kr(vals[i]))}</div>` };
  }, () => { cross.setAttribute('opacity', 0); dot.setAttribute('opacity', 0); });
}

/** Pointer/touch crosshair. Hit target is the whole plot, not the 2px line. */
function attachHover(svg, tip, at, off) {
  const wrap = svg.parentElement;
  const move = e => {
    const r = svg.getBoundingClientRect();
    const frac = Math.max(0, Math.min(1, (e.clientX - r.left) / r.width));
    const res = at(frac);
    if (!res) return;
    tip.innerHTML = res.html;
    tip.style.left = `${res.x * r.width}px`;
    tip.style.top = `${res.y * r.height - 10}px`;
    tip.classList.add('on');
  };
  const end = () => { tip.classList.remove('on'); off && off(); };
  wrap.addEventListener('pointerdown', move);
  wrap.addEventListener('pointermove', e => { if (e.pointerType === 'mouse' || e.buttons) move(e); });
  wrap.addEventListener('pointerup', end);
  wrap.addEventListener('pointercancel', end);
  wrap.addEventListener('pointerleave', end);
}

/* ── Owned ───────────────────────────────────────────────────────────── */

const KIND_LABEL = { property: 'Property', vehicle: 'Vehicle', other: 'Other' };

function renderOwned() {
  const items = Array.isArray(snap.assets) ? snap.assets : [];
  const loans = Array.isArray(snap.loans) ? snap.loans : [];
  if (!items.length && !loans.length) {
    paneEmpty('pane-owned',
      'Nothing is listed in assets.json yet — add the home, a car or anything else you own and it appears here.');
    return;
  }
  paneFilled('pane-owned');

  const worth = items.reduce((a, i) => a + (i.value || 0), 0);
  const owed = loans.reduce((a, l) => a + (l.balance || 0), 0);

  $('own-value').textContent = kr(worth + owed);
  $('own-assets').textContent = kr(worth);
  const ln = $('own-loans');
  ln.textContent = kr(Math.abs(owed));
  ln.className = 'v num' + (owed ? ' neg' : '');

  const d = $('own-delta');
  d.innerHTML = '';
  const yr = items.reduce((a, i) => a + (typeof i.change365d === 'number' ? i.change365d : 0), 0);
  const known = items.some(i => typeof i.change365d === 'number');
  if (known) {
    d.append(el('b', yr >= 0 ? 'pos' : 'neg', krSigned(yr)),
      document.createTextNode(' in value over a year, before the loan moved'));
  }

  const host = $('own-items');
  $('own-items-card').hidden = !items.length;
  host.innerHTML = '';
  for (const i of [...items].sort((a, b) => b.value - a.value)) {
    const r = el('div', 'row');
    const main = el('div', 'main');
    main.appendChild(el('div', 'nm', i.name));
    const bits = [KIND_LABEL[i.kind] || i.kind];
    if (i.anchorDate) bits.push(`anchored ${monthYear(i.anchorDate)}`);
    main.appendChild(el('div', 'meta', bits.join(' · ')));
    // The method is the caveat, so it is on screen rather than in a file.
    main.appendChild(el('div', 'basis', i.basis || ''));

    // Where the same thing can be valued more than one defensible way, the
    // choice belongs to whoever is reading, not to the file.
    if (Array.isArray(i.variants) && i.variants.length > 1) {
      const active = basisChoice[i.id] || i.variants[0].id;
      const sw = el('div', 'basis-switch');
      i.variants.forEach((v, n) => {
        const b = el('button', 'chip' + (v.id === active ? ' on' : ''), v.label || v.id);
        b.type = 'button';
        b.setAttribute('aria-pressed', String(v.id === active));
        b.title = `${v.basis || ''} — ${kr(v.value)}`;
        b.addEventListener('click', () => chooseBasis(i.id, v.id, n === 0));
        sw.appendChild(b);
      });
      main.appendChild(sw);
    }
    r.appendChild(main);

    const amt = el('div', 'amount', kr(i.value));
    if (typeof i.changeSinceAnchor === 'number' && i.anchorValue) {
      const g = i.changeSinceAnchor;
      const sm = el('span', 'sm', `${krSigned(g)} (${pct(g / i.anchorValue, 0)})`);
      sm.style.color = g >= 0 ? 'var(--pos)' : 'var(--neg)';
      amt.appendChild(sm);
    }
    r.appendChild(amt);
    host.appendChild(r);
  }

  const lhost = $('own-loanlist');
  $('own-loans-card').hidden = !loans.length;
  lhost.innerHTML = '';
  for (const l of loans) {
    const box = el('div', 'cat');
    const top = el('div', 'top');
    top.appendChild(el('div', 'nm', l.name));
    top.appendChild(el('div', 'amount neg', kr(l.balance)));
    box.appendChild(top);

    const track = el('div', 'track');
    const fill = el('div', 'fill is-loan');
    const done = Math.max(0, Math.min(1, l.paidOff || 0));
    fill.style.width = `${Math.max(1.5, done * 100)}%`;
    track.appendChild(fill);
    box.appendChild(track);

    const foot = el('div', 'foot');
    foot.appendChild(el('span', null, `${pct(done, 1)} of ${kr(l.principal)} repaid`));
    if (l.monthlyPayment) foot.appendChild(el('span', null, `${kr(l.monthlyPayment)}/mo`));
    if (typeof l.nominalRate === 'number') foot.appendChild(el('span', null, `${pct(l.nominalRate, 2)} nominal`));
    box.appendChild(foot);
    box.appendChild(el('div', 'basis', l.basis || ''));
    lhost.appendChild(box);
  }

  drawOwned();
}

/** What you own against what you owe on it, from the same history the net worth
 *  line uses — two series, so a legend, and only the endpoints direct-labelled. */
function drawOwned() {
  const h = snap.history;
  const card = $('own-chart-card');
  if (!Array.isArray(h.assets) || h.assets.length !== h.days.length) {
    card.hidden = true;
    return;
  }
  card.hidden = false;

  const n = h.days.length;
  const own = h.assets;
  const owe = h.liabilities.map(v => Math.abs(v));
  $('own-sub').textContent = `${fullDay(h.days[0])} to ${fullDay(h.days[n - 1])}. `
    + `The gap between them is the part of your net worth that is bricks and metal.`;

  const svg = $('own-chart');
  svg.innerHTML = '';
  const W = 320, H = 150, L = 42, R = 6, T = 10, B = 20;
  const iw = W - L - R, ih = H - T - B;
  let lo = 0, hi = Math.max(...own, ...owe);
  const ticks = niceTicks(lo, hi, 4);
  lo = Math.min(lo, ticks[0]); hi = Math.max(hi, ticks[ticks.length - 1]);

  const X = i => L + (n === 1 ? iw / 2 : (i / (n - 1)) * iw);
  const Y = v => T + ih - ((v - lo) / (hi - lo)) * ih;

  for (const t of ticks) {
    svg.appendChild(svgEl('line', { class: 'grid', x1: L, x2: W - R, y1: Y(t).toFixed(2), y2: Y(t).toFixed(2) }));
    const tx = svgEl('text', { x: L - 6, y: (Y(t) + 3.4).toFixed(2), 'text-anchor': 'end' });
    tx.textContent = krAxis(t, ticks.step);
    svg.appendChild(tx);
  }

  const path = arr => arr.map((v, i) => `${X(i).toFixed(2)},${Y(v).toFixed(2)}`).join(' ');
  svg.appendChild(svgEl('polyline', {
    points: path(own), fill: 'none', stroke: SERIES(4), 'stroke-width': 2, 'stroke-linecap': 'round'
  }));
  svg.appendChild(svgEl('polyline', {
    points: path(owe), fill: 'none', stroke: SERIES(2), 'stroke-width': 2, 'stroke-linecap': 'round'
  }));

  const f = svgEl('text', { x: L, y: H - 5 }); f.textContent = dayLabel(h.days[0]);
  const l = svgEl('text', { x: W - R, y: H - 5, 'text-anchor': 'end' }); l.textContent = dayLabel(h.days[n - 1]);
  svg.append(f, l);

  const cross = svgEl('line', { class: 'axis', y1: T, y2: T + ih, opacity: 0 });
  svg.appendChild(cross);
  attachHover(svg, $('own-tip'), frac => {
    const i = Math.max(0, Math.min(n - 1, Math.round(frac * (n - 1))));
    cross.setAttribute('x1', X(i)); cross.setAttribute('x2', X(i)); cross.setAttribute('opacity', 1);
    return {
      x: X(i) / W, y: Y(Math.max(own[i], owe[i])) / H,
      html: `<div class="t">${esc(fullDay(h.days[i]))}</div>`
        + `<div class="v">${esc(kr(own[i]))} <small>owned</small></div>`
        + `<div class="v">${esc(kr(owe[i]))} <small>owed</small></div>`
        + `<div class="v"><small>net</small> ${esc(kr(own[i] - owe[i]))}</div>`
    };
  }, () => cross.setAttribute('opacity', 0));

  const lg = $('own-legend');
  lg.innerHTML = '';
  lg.append(legendItem(SERIES(4), 'Owned', kr(own[n - 1])),
            legendItem(SERIES(2), 'Owed', kr(owe[n - 1])));
}

/* ── Spending ────────────────────────────────────────────────────────── */

function renderSpending() {
  const s = snap.spending;
  if (!s || !Array.isArray(s.categories) || !s.categories.length) {
    paneEmpty('pane-spending', 'This snapshot carries no spending breakdown.');
    return;
  }
  paneFilled('pane-spending');

  $('sp-label').textContent = `Spent in ${s.windowDays || 30} days`;
  $('sp-value').textContent = kr(s.total);

  const d = $('sp-delta'); d.innerHTML = '';
  if (typeof s.previousTotal === 'number' && s.previousTotal > 0) {
    const diff = s.total - s.previousTotal;
    // Spending up is the unwelcome direction, so the sign flips relative to net worth.
    d.append(el('b', diff <= 0 ? 'pos' : 'neg', krSigned(diff)),
      document.createTextNode(` against the ${s.windowDays || 30} days before`));
  }

  $('sp-sub').textContent = s.from && s.to
    ? `${fullDay(s.from)} to ${fullDay(s.to)}. Ranked by size.`
    : 'Ranked by size.';

  // One measure across nominal categories is ONE series, so every bar is one
  // colour — hue here would only re-encode the bar length.
  const cats = [...s.categories].sort((a, b) => b.amount - a.amount);
  const max = Math.max(...cats.map(c => c.amount), 1);
  const host = $('sp-cats'); host.innerHTML = '';

  for (const c of cats) {
    const box = el('div', 'cat');
    const top = el('div', 'top');
    top.appendChild(el('div', 'nm', c.label || c.id));
    top.appendChild(el('div', 'amount', kr(c.amount)));
    box.appendChild(top);

    const track = el('div', 'track');
    const fill = el('div', 'fill');
    fill.style.width = `${Math.max(1.5, (c.amount / max) * 100)}%`;
    track.appendChild(fill);
    box.appendChild(track);

    const foot = el('div', 'foot');
    foot.appendChild(el('span', null, `${c.count || 0} ${c.count === 1 ? 'payment' : 'payments'}`));
    if (typeof c.previous === 'number' && c.previous > 0) {
      const diff = c.amount - c.previous;
      foot.appendChild(Math.abs(diff) < 1
        ? el('span', null, 'unchanged')
        : el('span', diff < 0 ? 'pos' : 'neg', `${krSigned(diff)} vs previous`));
    }
    box.appendChild(foot);
    host.appendChild(box);
  }

  const mh = $('sp-merchants');
  const merch = Array.isArray(s.merchants) ? s.merchants : [];
  $('sp-merch-card').hidden = !merch.length;
  mh.innerHTML = '';
  for (const m of merch.slice(0, 12)) {
    const r = el('div', 'row');
    const main = el('div', 'main');
    main.appendChild(el('div', 'nm', m.label));
    main.appendChild(el('div', 'meta', `${m.count} ${m.count === 1 ? 'payment' : 'payments'}`));
    r.append(main, el('div', 'amount', kr(m.amount)));
    mh.appendChild(r);
  }
}

/* ── Cash flow ───────────────────────────────────────────────────────── */

function renderFlow() {
  const cf = snap.cashflow;
  const rec0 = Array.isArray(snap.recurring) ? snap.recurring : [];
  if ((!cf || !Array.isArray(cf.months) || !cf.months.length) && !rec0.length) {
    paneEmpty('pane-flow', 'This snapshot carries no monthly cash flow.');
    return;
  }
  paneFilled('pane-flow');

  const cfCard = $('cf-chart').closest('.card');
  cfCard.hidden = !(cf && Array.isArray(cf.months) && cf.months.length);
  if (!cfCard.hidden) drawCashflow(cf);

  const rec = Array.isArray(snap.recurring) ? snap.recurring : [];
  $('rec-card').hidden = !rec.length;
  const host = $('recurring'); host.innerHTML = '';
  for (const r of rec) {
    const row = el('div', 'row');
    const main = el('div', 'main');
    main.appendChild(el('div', 'nm', r.label));
    const bits = [r.cadence || 'repeating'];
    if (r.nextExpected) bits.push(`next ${dayLabel(r.nextExpected)}`);
    else if (r.lastSeen) bits.push(`last ${dayLabel(r.lastSeen)}`);
    main.appendChild(el('div', 'meta', bits.join(' · ')));
    row.append(main, el('div', 'amount' + (r.amount < 0 ? ' neg' : ' pos'), krSigned(r.amount)));
    host.appendChild(row);
  }
}

function drawCashflow(cf) {
  const svg = $('cf-chart');
  svg.innerHTML = '';
  const months = cf.months.slice(-12);
  const start = cf.months.length - months.length;
  const ins = (cf.in || []).slice(start);
  const outs = (cf.out || []).slice(start);
  const n = months.length;

  $('cf-sub').textContent = `${monthFull(months[0])} to ${monthFull(months[n - 1])}. Out is shown as a positive amount.`;

  const W = 320, H = 180, L = 42, R = 6, T = 12, B = 24;
  const iw = W - L - R, ih = H - T - B;
  const hi = Math.max(...ins, ...outs, 1);
  const ticks = niceTicks(0, hi, 4, true);   // bars need room above the tallest
  const top = Math.max(hi, ticks[ticks.length - 1]);
  const Y = v => T + ih - (v / top) * ih;

  for (const t of ticks) {
    svg.appendChild(svgEl('line', { class: 'grid', x1: L, x2: W - R, y1: Y(t).toFixed(2), y2: Y(t).toFixed(2) }));
    const tx = svgEl('text', { x: L - 6, y: (Y(t) + 3.4).toFixed(2), 'text-anchor': 'end' });
    tx.textContent = krAxis(t, ticks.step);
    svg.appendChild(tx);
  }

  const slot = iw / n;
  const GAP = 2;                       // surface gap between the paired bars
  const bw = Math.max(3, (slot * 0.62 - GAP) / 2);

  for (let i = 0; i < n; i++) {
    const cx = L + slot * (i + 0.5);
    const pairs = [[ins[i] || 0, SERIES(1), cx - GAP / 2 - bw], [outs[i] || 0, SERIES(2), cx + GAP / 2]];
    for (const [v, col, x] of pairs) {
      const y = Y(v), hgt = Math.max(v > 0 ? 1.5 : 0, T + ih - y);
      if (!hgt) continue;
      // Rounded at the data end only, so the bar stays anchored to the baseline.
      const r = Math.min(4, bw / 2, hgt);
      svg.appendChild(svgEl('path', {
        d: `M${x.toFixed(2)},${(T + ih).toFixed(2)} V${(y + r).toFixed(2)} Q${x.toFixed(2)},${y.toFixed(2)} ${(x + r).toFixed(2)},${y.toFixed(2)} H${(x + bw - r).toFixed(2)} Q${(x + bw).toFixed(2)},${y.toFixed(2)} ${(x + bw).toFixed(2)},${(y + r).toFixed(2)} V${(T + ih).toFixed(2)} Z`,
        fill: col
      }));
    }
    if (n <= 12 || i % 2 === 0) {
      const tx = svgEl('text', { x: cx.toFixed(2), y: H - 8, 'text-anchor': 'middle' });
      tx.textContent = monthLabel(months[i]);
      svg.appendChild(tx);
    }
  }

  svg.appendChild(svgEl('line', { class: 'axis', x1: L, x2: W - R, y1: T + ih, y2: T + ih }));

  const band = svgEl('rect', { y: T, height: ih, width: slot, fill: 'var(--ink)', opacity: 0, id: 'cf-band' });
  svg.insertBefore(band, svg.firstChild);

  attachHover(svg, $('cf-tip'), frac => {
    const plotFrac = (frac * W - L) / iw;              // 0 at the first slot, 1 past the last
    const i = Math.max(0, Math.min(n - 1, Math.floor(plotFrac * n)));
    band.setAttribute('x', L + slot * i); band.setAttribute('opacity', .05);
    const net = (ins[i] || 0) - (outs[i] || 0);
    return {
      x: (L + slot * (i + 0.5)) / W, y: T / H,
      html: `<div class="t">${esc(monthFull(months[i]))}</div>`
        + `<div class="v">${esc(kr(ins[i] || 0))} <small>in</small></div>`
        + `<div class="v">${esc(kr(outs[i] || 0))} <small>out</small></div>`
        + `<div class="v"><small>net</small> ${esc(krSigned(net))}</div>`
    };
  }, () => band.setAttribute('opacity', 0));

  const totIn = ins.reduce((a, b) => a + b, 0), totOut = outs.reduce((a, b) => a + b, 0);
  const lg = $('cf-legend'); lg.innerHTML = '';
  lg.append(legendItem(SERIES(1), 'In', kr(totIn / n) + ' / mo'),
            legendItem(SERIES(2), 'Out', kr(totOut / n) + ' / mo'));

  const tbl = $('cf-table');
  tbl.innerHTML = '<thead><tr><th>Month</th><th class="n">In</th><th class="n">Out</th><th class="n">Net</th></tr></thead>';
  const body = el('tbody');
  for (let i = n - 1; i >= 0; i--) {
    const tr = el('tr');
    tr.appendChild(el('td', null, monthFull(months[i])));
    tr.appendChild(el('td', 'n', kr(ins[i] || 0)));
    tr.appendChild(el('td', 'n', kr(outs[i] || 0)));
    const net = (ins[i] || 0) - (outs[i] || 0);
    tr.appendChild(el('td', 'n' + (net >= 0 ? ' pos' : ' neg'), krSigned(net)));
    body.appendChild(tr);
  }
  tbl.appendChild(body);
}

function legendItem(color, label, value) {
  const it = el('div', 'item');
  const sw = el('span', 'swatch'); sw.style.background = color;
  it.append(sw, el('span', null, label));
  if (value) it.append(el('b', null, value));
  return it;
}

/* ── Savings ─────────────────────────────────────────────────────────── */

function renderSavings() {
  const inv = snap.investments;
  const eq = snap.equity;
  const pen = snap.pension;
  const hasFunds = inv && Array.isArray(inv.funds) && inv.funds.length;
  const hasEquity = eq && Array.isArray(eq.grants) && eq.grants.length;
  const hasPension = pen && Array.isArray(pen.accounts) && pen.accounts.length;
  if (!hasFunds && !hasEquity && !hasPension) {
    paneEmpty('pane-savings', 'No investments are tracked in this snapshot.');
    return;
  }
  paneFilled('pane-savings');

  // Headline covers all three holdings; each keeps its own section below.
  const fundsTotal = hasFunds ? (inv.total || 0) : 0;
  const eqTotal = hasEquity ? (eq.counted || 0) : 0;
  const penTotal = hasPension ? (pen.total || 0) : 0;
  // Only compare like with like. An employer's pension account is anchored to
  // a value with no record of what went in, so counting it against a cost of
  // nothing would report the whole balance as profit.
  const priced = [];
  if (hasFunds) priced.push({ value: fundsTotal, cost: inv.costBasis || 0 });
  if (hasEquity) priced.push({ value: eqTotal, cost: eq.costBasis || 0 });
  let unknownCost = 0;
  if (hasPension) for (const a of pen.accounts) {
    if (a.costBasis > 0) priced.push({ value: a.value || 0, cost: a.costBasis });
    else unknownCost += a.value || 0;
  }
  const cost = priced.reduce((a, p) => a + p.cost, 0);
  const gain = priced.reduce((a, p) => a + p.value, 0) - cost;

  $('inv-value').textContent = kr(fundsTotal + eqTotal + penTotal);
  $('inv-funds-tot').textContent = hasFunds ? kr(fundsTotal) : '—';
  $('inv-equity-tot').textContent = hasEquity ? kr(eqTotal) : '—';
  $('inv-pension-tot').textContent = hasPension ? kr(penTotal) : '—';
  $('inv-cost').textContent = kr(cost);

  renderPension(pen, hasPension);

  // A percentage return is only meaningful if everything in the total was
  // bought. RSUs are granted, so once they are in it, "91 % on what you paid
  // in" is an artefact of dividing by a cost that was never paid.
  const granted = hasEquity && eq.grants.some(g =>
    (g.vestedShares || 0) + (g.unvestedShares || 0) > 0 && !(g.costBasis > 0));

  const d = $('inv-delta'); d.innerHTML = '';
  if (cost > 0 && !granted) {
    d.append(el('b', gain >= 0 ? 'pos' : 'neg', krSigned(gain)),
      document.createTextNode(` · ${pct(gain / cost)} on what you paid in`));
    if (unknownCost > 0)
      d.append(document.createTextNode(`, on all but the ${kr(unknownCost)} of pension`
        + ' whose contributions are not recorded here'));
  } else if (cost > 0) {
    d.append(el('b', gain >= 0 ? 'pos' : 'neg', krSigned(gain)),
      document.createTextNode(' above what you paid — some of these shares were granted, not bought'));
  } else {
    d.textContent = 'All of this was granted rather than bought.';
  }

  renderEquity(eq, hasEquity);

  const fundCards = ['funds-head', 'inv-drift', 'inv-alloc-card', 'inv-growth-card'];
  for (const id of fundCards) { const n = $(id); if (n) n.hidden = !hasFunds; }
  const fundsCard = $('inv-funds') && $('inv-funds').closest('.card');
  if (fundsCard) fundsCard.hidden = !hasFunds;
  if (!hasFunds) return;

  // Accrued units drift. Saying so is the difference between an estimate and a
  // number pretending to be a fact.
  const drift = $('inv-drift'); drift.innerHTML = '';

  // A fund counted as zero because nothing would price it is not a fund worth
  // zero, and a total quietly missing one is worse than a total that says so.
  if (Array.isArray(inv.unpriced) && inv.unpriced.length) {
    const b = el('div', 'banner bad');
    b.appendChild(el('span', 'dot'));
    b.appendChild(el('span', null,
      `No price could be found for ${inv.unpriced.join(', ')}, so ${inv.unpriced.length === 1 ? 'it is' : 'they are'} `
      + 'counted as nothing in the total above. Set a navSource that resolves, or a manual price.'));
    drift.appendChild(b);
  }

  if (inv.anchoredAt) {
    const age = daysBetween(inv.anchoredAt, new Date().toISOString().slice(0, 10));
    const stale = age > 120;
    const b = el('div', stale ? 'banner warn' : 'banner');
    if (!stale) { b.style.background = 'var(--chip)'; b.style.color = 'var(--ink-dim)'; }
    b.appendChild(el('span', 'dot'));
    b.appendChild(el('span', null,
      `Units last checked against your fund provider ${age} ${age === 1 ? 'day' : 'days'} ago`
      + (inv.accruedSince ? `, ${inv.accruedSince} purchases accrued since` : '')
      + (stale ? '. Worth pasting the real unit counts from your provider into holdings.json.' : '.')));
    drift.appendChild(b);
  }

  drawAllocation(inv.funds);

  $('inv-sub').textContent = inv.funds[0] && inv.funds[0].navDate
    ? `Priced at NAV of ${fullDay(inv.funds[0].navDate)}.` : '';

  const host = $('inv-funds'); host.innerHTML = '';
  for (const f of [...inv.funds].sort((a, b) => b.value - a.value)) {
    const priced = typeof f.nav === 'number' && f.nav > 0;
    const r = el('div', 'row');
    const main = el('div', 'main');
    main.appendChild(el('div', 'nm', f.name));
    const bits = [`${nf(f.units, 4)} units`];
    if (priced) bits.push(`NAV ${nf(f.nav, 2)}`);
    if (f.navSource === 'stale') bits.push('price is stale');
    if (f.navSource === 'unavailable') bits.push('no price found');
    if (f.navSource === 'manual') bits.push('price entered by hand');
    main.appendChild(el('div', 'meta', bits.join(' · ')));
    r.appendChild(main);

    // An unpriced fund is not a fund that lost everything. Showing "0 kr" beside
    // "−100 %" in red says exactly that, so neither figure is drawn at all.
    const amt = el('div', 'amount', priced ? kr(f.value) : '—');
    if (!priced) {
      amt.appendChild(el('span', 'sm', 'not counted'));
    } else if (typeof f.costBasis === 'number' && f.costBasis > 0) {
      const g = f.value - f.costBasis;
      const sm = el('span', 'sm', `${krSigned(g)} (${pct(g / f.costBasis, 0)})`);
      sm.style.color = g >= 0 ? 'var(--pos)' : 'var(--neg)';
      amt.appendChild(sm);
    }
    r.appendChild(amt);
    host.appendChild(r);
  }

  // A chart drawn from units alone is not a chart of the market, and saying so
  // is the difference between an estimate and a number pretending to be one.
  if (inv.historyBasis === 'contributions' || inv.historyBasis === 'mixed') {
    const b = el('div', 'banner warn');
    b.appendChild(el('span', 'dot'));
    b.appendChild(el('span', null, inv.historyBasis === 'contributions'
      ? 'No price history was available, so the line below moves only as money goes in — the market’s part of it is missing.'
      : 'Only some funds carry price history, so the line below is part market and part contributions.'));
    drift.appendChild(b);
  }

  drawInvGrowth(inv);
}

function drawAllocation(funds) {
  const svg = $('inv-alloc');
  svg.innerHTML = '';
  const total = funds.reduce((a, f) => a + f.value, 0) || 1;

  // Slots are fixed and never cycled: past six funds the tail folds into Other.
  const sorted = [...funds].sort((a, b) => b.value - a.value);
  const shown = sorted.slice(0, 5);
  const rest = sorted.slice(5);
  const segs = shown.map((f, i) => ({ label: f.name, value: f.value, color: SERIES(i + 1) }));
  if (rest.length) segs.push({
    label: `Other (${rest.length})`, value: rest.reduce((a, f) => a + f.value, 0), color: SERIES(6)
  });

  const W = 320, H = 34, GAP = 2, h = 20;
  let x = 0;
  for (const s of segs) {
    const w = Math.max(2, (s.value / total) * (W - GAP * (segs.length - 1)));
    svg.appendChild(svgEl('rect', { x: x.toFixed(2), y: 0, width: w.toFixed(2), height: h, rx: 4, fill: s.color }));
    // The relief rule: three light-mode slots sit under 3:1, so the share is
    // written on the bar wherever it fits and always in the legend.
    if (w > 40) {
      const tx = svgEl('text', { x: (x + w / 2).toFixed(2), y: h + 12, 'text-anchor': 'middle', class: 'dlabel' });
      tx.textContent = pct(s.value / total, 0);
      svg.appendChild(tx);
    }
    x += w + GAP;
  }

  const lg = $('inv-legend'); lg.innerHTML = '';
  for (const s of segs) lg.appendChild(legendItem(s.color, s.label, kr(s.value)));
}

function drawInvGrowth(inv) {
  const card = $('inv-growth-card');
  const ser = inv.series;
  if (!ser || !Array.isArray(ser.days) || ser.days.length < 2
      || !Array.isArray(ser.value) || ser.value.length !== ser.days.length) {
    card.hidden = true;
    return;
  }
  card.hidden = false;
  const svg = $('inv-chart');
  svg.innerHTML = '';
  const days = ser.days, val = ser.value;
  const con = Array.isArray(ser.contributed) && ser.contributed.length === days.length ? ser.contributed : null;
  const n = days.length;

  const W = 320, H = 150, L = 42, R = 6, T = 10, B = 20;
  const iw = W - L - R, ih = H - T - B;
  const all = con ? val.concat(con) : val;
  let lo = Math.min(...all, 0), hi = Math.max(...all);
  const ticks = niceTicks(lo, hi, 4);
  lo = Math.min(lo, ticks[0]); hi = Math.max(hi, ticks[ticks.length - 1]);

  const X = i => L + (i / (n - 1)) * iw;
  const Y = v => T + ih - ((v - lo) / (hi - lo)) * ih;

  for (const t of ticks) {
    svg.appendChild(svgEl('line', { class: 'grid', x1: L, x2: W - R, y1: Y(t).toFixed(2), y2: Y(t).toFixed(2) }));
    const tx = svgEl('text', { x: L - 6, y: (Y(t) + 3.4).toFixed(2), 'text-anchor': 'end' });
    tx.textContent = krAxis(t, ticks.step);
    svg.appendChild(tx);
  }

  if (con) svg.appendChild(svgEl('polyline', {
    points: con.map((v, i) => `${X(i).toFixed(2)},${Y(v).toFixed(2)}`).join(' '),
    fill: 'none', stroke: SERIES(2), 'stroke-width': 2, 'stroke-linecap': 'round'
  }));
  svg.appendChild(svgEl('polyline', {
    points: val.map((v, i) => `${X(i).toFixed(2)},${Y(v).toFixed(2)}`).join(' '),
    fill: 'none', stroke: SERIES(1), 'stroke-width': 2, 'stroke-linecap': 'round'
  }));

  const f = svgEl('text', { x: L, y: H - 5 }); f.textContent = dayLabel(days[0]);
  const l = svgEl('text', { x: W - R, y: H - 5, 'text-anchor': 'end' }); l.textContent = dayLabel(days[n - 1]);
  svg.append(f, l);

  const cross = svgEl('line', { class: 'axis', y1: T, y2: T + ih, opacity: 0 });
  svg.appendChild(cross);
  attachHover(svg, $('inv-tip'), frac => {
    const i = Math.max(0, Math.min(n - 1, Math.round(frac * (n - 1))));
    cross.setAttribute('x1', X(i)); cross.setAttribute('x2', X(i)); cross.setAttribute('opacity', 1);
    return {
      x: X(i) / W, y: Y(Math.max(val[i], con ? con[i] : val[i])) / H,
      html: `<div class="t">${esc(fullDay(days[i]))}</div>`
        + `<div class="v">${esc(kr(val[i]))} <small>value</small></div>`
        + (con ? `<div class="v">${esc(kr(con[i]))} <small>paid in</small></div>` : '')
    };
  }, () => cross.setAttribute('opacity', 0));

  const lg = $('inv-glegend'); lg.innerHTML = '';
  lg.append(legendItem(SERIES(1), 'Value', kr(val[n - 1])));
  if (con) lg.append(legendItem(SERIES(2), 'Paid in', kr(con[n - 1])));
}

const GRANT_LABEL = { rsu: 'RSU', psu: 'PSU', espp: 'ESPP', option: 'Options', share: 'Shares' };

/** Who the exchange rate came from. Norges Bank publishes its reference rates
 *  under NLOD, which asks that the source be credited — so the credit is
 *  printed beside the rate it produced rather than buried in a notes file. */
const FX_SOURCE_LABEL = { 'norges-bank': 'Norges Bank', manual: 'typed in', inline: 'from the file' };

/** Employee shares. Nothing here is fetched from the plan administrator — the
 *  share counts are copied out once and the calendar does the rest, so the one
 *  thing worth showing prominently is which tranches have actually landed. */
function renderEquity(eq, has) {
  for (const id of ['eq-head', 'eq-card', 'eq-grants-card', 'eq-vest-card']) {
    const n = $(id);
    if (n) n.hidden = !has;
  }
  if (!has) return;

  $('eq-title').textContent = eq.provider || 'Employee shares';
  const price = typeof eq.price === 'number'
    ? `${eq.symbol || 'Share'} at ${nf(eq.price, 2)} ${eq.currency}` : 'Price unavailable';
  const fxCredit = FX_SOURCE_LABEL[eq.fxSource] || eq.fxSource;
  const fx = typeof eq.fxRate === 'number' && eq.currency !== 'NOK'
    ? ` · ${nf(eq.fxRate, 4)} NOK/${eq.currency}${fxCredit ? ` (${fxCredit})` : ''}` : '';
  const when = eq.priceDate ? ` · ${fullDay(eq.priceDate)}` : '';
  $('eq-sub').textContent = price + fx + when;

  const host = $('eq-summary');
  host.innerHTML = '';

  if (eq.error) {
    const b = el('div', 'banner bad');
    b.appendChild(el('span', 'dot'));
    b.appendChild(el('span', null, `These shares are not in your net worth: ${eq.error}.`));
    host.appendChild(b);
  }

  host.appendChild(summaryRow('Vested',
    `${nf(eq.vestedShares, 0)} shares · yours now`, eq.vested, true));

  if (eq.unvestedShares > 0) {
    // An unvested RSU is a promise, and in Norway it is taxed as salary the
    // moment it lands — so saying what it is worth means saying both things.
    const meta = eq.includeUnvested
      ? `${nf(eq.unvestedShares, 0)} shares · counted after ${pct(eq.unvestedTaxRate, 0)} tax`
      : `${nf(eq.unvestedShares, 0)} shares · not counted in net worth`;
    const row = summaryRow('Not vested yet', meta,
      eq.includeUnvested ? eq.unvestedAfterTax : eq.unvested, false);
    if (!eq.includeUnvested) row.style.opacity = '.7';
    host.appendChild(row);
  }

  host.appendChild(summaryRow('In your net worth',
    eq.includeUnvested ? 'vested, plus unvested after tax' : 'vested shares only',
    eq.counted, true));

  if (eq.historyBasis === 'flat' || eq.historyBasis === 'partial') {
    const b = el('div', 'banner warn');
    b.appendChild(el('span', 'dot'));
    b.appendChild(el('span', null, eq.historyBasis === 'flat'
      ? 'No price or exchange-rate history was available, so past values move only as tranches vest.'
      : 'Only one of the price and the exchange rate carries history, so part of the past line is held flat.'));
    host.appendChild(b);
  }

  const gh = $('eq-grants');
  gh.innerHTML = '';
  for (const g of eq.grants) {
    const r = el('div', 'row');
    const main = el('div', 'main');
    main.appendChild(el('div', 'nm', g.label));
    const bits = [GRANT_LABEL[g.kind] || g.kind];
    if (g.unvestedShares > 0 && g.nextVest) bits.push(`next ${monthYear(g.nextVest)}`);
    else if (g.unvestedShares === 0) bits.push('fully vested');
    if (g.kind === 'option' && typeof g.strike === 'number')
      bits.push(`strike ${nf(g.strike, 2)} ${eq.currency}`);
    main.appendChild(el('div', 'meta', bits.join(' · ')));
    if (g.underWater) main.appendChild(el('div', 'basis', 'Under water — worth nothing at this price.'));
    r.appendChild(main);

    const amt = el('div', 'amount', kr(g.vested));
    if (g.unvestedShares > 0)
      amt.appendChild(el('span', 'sm', `+ ${kr(g.unvested)} to come`));
    r.append(amt);
    gh.appendChild(r);
  }

  const vh = $('eq-vest');
  vh.innerHTML = '';
  const upcoming = Array.isArray(eq.upcoming) ? eq.upcoming : [];
  $('eq-vest-card').hidden = !upcoming.length;
  if (upcoming.length) {
    $('eq-vest-sub').textContent = 'Valued at today’s price — what it is actually worth '
      + 'depends on the price on the day, and tax comes off it.';
    for (const u of upcoming) {
      const r = el('div', 'row');
      const main = el('div', 'main');
      main.appendChild(el('div', 'nm', fullDay(u.date)));
      const days = daysBetween(new Date().toISOString().slice(0, 10), u.date);
      main.appendChild(el('div', 'meta',
        `${nf(u.shares, 0)} shares · ${u.label} · in ${days} days`));
      r.append(main, el('div', 'amount', kr(u.value)));
      vh.appendChild(r);
    }
  }
}

/** Pension: its own section, because it is its own kind of money — counted in
    net worth, but not reachable for decades, and part of it an estimate rather
    than a reading. Each account says which of the two it is and how old its
    anchor is, so nothing here can pass for a live figure when it is not. */
function renderPension(pen, has) {
  for (const id of ['pen-head', 'pen-card']) { const n = $(id); if (n) n.hidden = !has; }
  if (!has) return;

  const sub = [];
  if (!pen.includeInNetWorth) sub.push('Shown here but NOT counted in net worth.');
  sub.push(pen.accounts.length === 1 ? 'One account.' : `${pen.accounts.length} accounts.`);
  if (Array.isArray(pen.notes) && pen.notes.length) sub.push(pen.notes.join(' '));
  $('pen-sub').textContent = sub.join(' ');

  const host = $('pen-accounts');
  host.innerHTML = '';
  for (const a of [...pen.accounts].sort((x, y) => (y.value || 0) - (x.value || 0))) {
    const r = el('div', 'row');
    const main = el('div', 'main');
    main.appendChild(el('div', 'nm', a.label || a.id));
    const bits = [];
    if (a.provider) bits.push(a.provider);
    if (a.accruedSince) bits.push(`${a.accruedSince} payment${a.accruedSince === 1 ? '' : 's'} since the anchor`);
    if (a.note) bits.push(a.note);
    main.appendChild(el('div', 'meta', bits.join(' · ')));
    // How this number was arrived at, in the same place every other estimate
    // in this app declares itself.
    main.appendChild(el('div', 'basis', a.basis || ''));
    r.appendChild(main);

    const amt = el('div', 'amount', kr(a.value));
    if (a.costBasis > 0) {
      const g = (a.value || 0) - a.costBasis;
      const sm = el('span', 'sm', `${krSigned(g)} (${pct(g / a.costBasis, 0)})`);
      sm.style.color = g >= 0 ? 'var(--pos)' : 'var(--neg)';
      amt.appendChild(sm);
    }
    r.appendChild(amt);
    host.appendChild(r);
  }

  // The funds inside each account, where the account is priced from units.
  const fh = $('pen-funds');
  fh.innerHTML = '';
  for (const a of pen.accounts) {
    for (const f of a.funds || []) {
      fh.appendChild(summaryRow(
        f.name || 'Fund',
        `${a.label} · ${nf(f.units, 4)} units` + (f.nav ? ` at ${kr(f.nav, 2)}` : '')
        + (f.navSource && f.navSource !== 'yahoo' ? ` · ${f.navSource}` : ''),
        f.value));
    }
  }
}

function summaryRow(name, meta, value, strong) {
  const r = el('div', 'row');
  const main = el('div', 'main');
  main.appendChild(el('div', 'nm', name));
  main.appendChild(el('div', 'meta', meta));
  r.append(main, el('div', 'amount', kr(value)));
  if (!strong) r.querySelector('.amount').style.fontWeight = '540';
  return r;
}

/* ── Transactions ────────────────────────────────────────────────────── */

function renderTxns() {
  const list = $('tx-list');
  list.innerHTML = '';
  const all = Array.isArray(snap.transactions) ? snap.transactions : [];
  if (!all.length) {
    list.appendChild(el('div', 'empty', 'This snapshot carries no transactions.'));
    return;
  }

  const q = txQuery.trim().toLowerCase();
  const rows = q
    ? all.filter(t => `${t.text} ${t.account} ${t.category} ${catLabel(t.category)} ${t.source}`
        .toLowerCase().includes(q))
    : all;

  if (!rows.length) {
    list.appendChild(el('div', 'empty', `Nothing matches “${txQuery}”.`));
    return;
  }

  let day = null, group = null;
  for (const t of rows.slice(0, txShown)) {
    if (t.date !== day) {
      day = t.date;
      group = el('div', 'daygroup');
      group.appendChild(el('div', 'd', fullDay(day)));
      list.appendChild(group);
    }
    const r = el('div', 'row');
    const main = el('div', 'main');
    main.appendChild(el('div', 'nm', t.text));
    main.appendChild(el('div', 'meta', [t.account, catLabel(t.category)].filter(Boolean).join(' · ')));
    r.append(main, el('div', 'amount' + (t.amount < 0 ? '' : ' pos'), krSigned(t.amount, 2)));
    group.appendChild(r);
  }

  if (rows.length > txShown) {
    const more = el('button', 'more', `Show ${Math.min(100, rows.length - txShown)} more of ${rows.length}`);
    more.addEventListener('click', () => { txShown += 100; renderTxns(); });
    list.appendChild(more);
  }
}

/* ── Wiring ──────────────────────────────────────────────────────────── */

$('tabs').addEventListener('click', e => {
  const b = e.target.closest('.tab');
  if (!b) return;
  showTab(b.dataset.pane);
});

function showTab(name) {
  document.querySelectorAll('.tab').forEach(t => {
    const on = t.dataset.pane === name;
    t.classList.toggle('is-active', on);
    t.setAttribute('aria-selected', on ? 'true' : 'false');
  });
  document.querySelectorAll('.pane').forEach(p =>
    p.classList.toggle('is-active', p.id === `pane-${name}`));
  localStorage.setItem(STORE_TAB, name);
  window.scrollTo({ top: 0 });
}

$('nw-range').addEventListener('click', e => {
  const b = e.target.closest('button');
  if (!b) return;
  range = +b.dataset.days;
  localStorage.setItem(STORE_RANGE, String(range));
  document.querySelectorAll('#nw-range button').forEach(x =>
    x.classList.toggle('is-active', x === b));
  drawNetWorth();
});

$('tx-search').addEventListener('input', e => {
  txQuery = e.target.value;
  txShown = 100;
  renderTxns();
});

$('reload').addEventListener('click', async () => {
  const b = $('reload');
  b.classList.add('spin');
  await load();
  setTimeout(() => b.classList.remove('spin'), 400);
});

/* Reads are always fresh from disk, so re-reading when the app comes back to
   the front is what makes an app opened this morning show this morning's data. */
document.addEventListener('visibilitychange', () => { if (!document.hidden) load(); });

const savedTab = localStorage.getItem(STORE_TAB);
if (savedTab && document.getElementById(`pane-${savedTab}`)) showTab(savedTab);

load();
